# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.cache/wt [current_project]
set_property parent.project_path C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/new/SPI.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/imports/verilog/capped_adder.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/new/clkDivider.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/new/getOmega.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/imports/verilog/sd2.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/imports/verilog/sd_two_piece.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/imports/verilog/sigma_delta_twopiece.v
  C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/sources_1/new/main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/constrs_1/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/trent/Coding/ECE224A/Final/Oscillator/Oscillator.srcs/constrs_1/Nexys-4-DDR-Master.xdc]


synth_design -top main -part xc7a200tfbg676-2


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
