/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID linux22.engr.ucsb.edu)
#  Generated on:      Tue Jun  9 00:50:18 2020
#  Design:            chip
#  Command:           saveNetlist -excludeLeafCell oscillator_chip_netlist_fpga.v
###############################################################
*/
module core (
	clk, 
	reset, 
	sd_out);
   input clk;
   input reset;
   output [1:0] sd_out;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire \piece_0/N49 ;
   wire \piece_0/N48 ;
   wire \piece_0/N47 ;
   wire \piece_0/N46 ;
   wire \piece_0/N45 ;
   wire \piece_0/N44 ;
   wire \piece_0/N43 ;
   wire \piece_0/N42 ;
   wire \piece_0/N41 ;
   wire \piece_0/N40 ;
   wire \piece_0/N39 ;
   wire \piece_0/N38 ;
   wire \piece_0/N37 ;
   wire \piece_0/N36 ;
   wire \piece_0/N35 ;
   wire \piece_0/N34 ;
   wire \piece_0/N33 ;
   wire \piece_0/N32 ;
   wire \piece_0/N31 ;
   wire \piece_0/N30 ;
   wire \piece_0/N29 ;
   wire \piece_0/N28 ;
   wire \piece_0/N27 ;
   wire \piece_0/N26 ;
   wire \piece_0/N25 ;
   wire \piece_0/N24 ;
   wire \piece_0/N23 ;
   wire \piece_0/N22 ;
   wire \piece_0/N21 ;
   wire \piece_0/N20 ;
   wire \piece_0/N19 ;
   wire \piece_0/N18 ;
   wire \piece_0/N17 ;
   wire \piece_0/N16 ;
   wire \piece_1/N49 ;
   wire \piece_1/N48 ;
   wire \piece_1/N47 ;
   wire \piece_1/N46 ;
   wire \piece_1/N45 ;
   wire \piece_1/N44 ;
   wire \piece_1/N43 ;
   wire \piece_1/N42 ;
   wire \piece_1/N41 ;
   wire \piece_1/N40 ;
   wire \piece_1/N39 ;
   wire \piece_1/N38 ;
   wire \piece_1/N37 ;
   wire \piece_1/N36 ;
   wire \piece_1/N35 ;
   wire \piece_1/N34 ;
   wire \piece_1/N33 ;
   wire \piece_1/N32 ;
   wire \piece_1/N31 ;
   wire \piece_1/N30 ;
   wire \piece_1/N29 ;
   wire \piece_1/N28 ;
   wire \piece_1/N27 ;
   wire \piece_1/N26 ;
   wire \piece_1/N25 ;
   wire \piece_1/N24 ;
   wire \piece_1/N23 ;
   wire \piece_1/N22 ;
   wire \piece_1/N21 ;
   wire \piece_1/N20 ;
   wire \piece_1/N19 ;
   wire \piece_1/N18 ;
   wire \piece_1/N17 ;
   wire \piece_1/N16 ;
   wire \piece_0/sd_one/N128 ;
   wire \piece_0/sd_one/N127 ;
   wire \piece_0/sd_one/N126 ;
   wire \piece_0/sd_one/N125 ;
   wire \piece_0/sd_one/N124 ;
   wire \piece_0/sd_one/N123 ;
   wire \piece_0/sd_one/N122 ;
   wire \piece_0/sd_one/N121 ;
   wire \piece_0/sd_one/N120 ;
   wire \piece_0/sd_one/N119 ;
   wire \piece_0/sd_one/N118 ;
   wire \piece_0/sd_one/N117 ;
   wire \piece_0/sd_one/N116 ;
   wire \piece_0/sd_one/N115 ;
   wire \piece_0/sd_one/N114 ;
   wire \piece_0/sd_one/N113 ;
   wire \piece_0/sd_one/N112 ;
   wire \piece_0/sd_one/N111 ;
   wire \piece_0/sd_one/N73 ;
   wire \piece_0/sd_one/N72 ;
   wire \piece_0/sd_one/N71 ;
   wire \piece_0/sd_one/N70 ;
   wire \piece_0/sd_one/N69 ;
   wire \piece_0/sd_one/N68 ;
   wire \piece_0/sd_one/N67 ;
   wire \piece_0/sd_one/N66 ;
   wire \piece_0/sd_one/N65 ;
   wire \piece_0/sd_one/N64 ;
   wire \piece_0/sd_one/N63 ;
   wire \piece_0/sd_one/N62 ;
   wire \piece_0/sd_one/N61 ;
   wire \piece_0/sd_one/N60 ;
   wire \piece_0/sd_one/N59 ;
   wire \piece_0/sd_one/N58 ;
   wire \piece_0/sd_one/N57 ;
   wire \piece_0/sd_one/N56 ;
   wire \piece_1/sd_one/N128 ;
   wire \piece_1/sd_one/N127 ;
   wire \piece_1/sd_one/N126 ;
   wire \piece_1/sd_one/N125 ;
   wire \piece_1/sd_one/N124 ;
   wire \piece_1/sd_one/N123 ;
   wire \piece_1/sd_one/N122 ;
   wire \piece_1/sd_one/N121 ;
   wire \piece_1/sd_one/N120 ;
   wire \piece_1/sd_one/N119 ;
   wire \piece_1/sd_one/N118 ;
   wire \piece_1/sd_one/N117 ;
   wire \piece_1/sd_one/N116 ;
   wire \piece_1/sd_one/N115 ;
   wire \piece_1/sd_one/N114 ;
   wire \piece_1/sd_one/N113 ;
   wire \piece_1/sd_one/N112 ;
   wire \piece_1/sd_one/N111 ;
   wire \piece_1/sd_one/N73 ;
   wire \piece_1/sd_one/N72 ;
   wire \piece_1/sd_one/N71 ;
   wire \piece_1/sd_one/N70 ;
   wire \piece_1/sd_one/N69 ;
   wire \piece_1/sd_one/N68 ;
   wire \piece_1/sd_one/N67 ;
   wire \piece_1/sd_one/N66 ;
   wire \piece_1/sd_one/N65 ;
   wire \piece_1/sd_one/N64 ;
   wire \piece_1/sd_one/N63 ;
   wire \piece_1/sd_one/N62 ;
   wire \piece_1/sd_one/N61 ;
   wire \piece_1/sd_one/N60 ;
   wire \piece_1/sd_one/N59 ;
   wire \piece_1/sd_one/N58 ;
   wire \piece_1/sd_one/N57 ;
   wire \piece_1/sd_one/N56 ;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n576;
   wire n577;
   wire n578;
   wire n579;
   wire n580;
   wire n581;
   wire n582;
   wire n583;
   wire n584;
   wire n585;
   wire n586;
   wire n587;
   wire n588;
   wire n589;
   wire n590;
   wire n591;
   wire n592;
   wire n593;
   wire n594;
   wire n595;
   wire n596;
   wire n597;
   wire n598;
   wire n599;
   wire n600;
   wire n601;
   wire n602;
   wire n603;
   wire n604;
   wire n605;
   wire n606;
   wire n607;
   wire n608;
   wire n609;
   wire n610;
   wire n611;
   wire n612;
   wire n613;
   wire n614;
   wire n615;
   wire n616;
   wire n617;
   wire n618;
   wire n619;
   wire n620;
   wire n621;
   wire n622;
   wire n623;
   wire n624;
   wire n625;
   wire n626;
   wire n627;
   wire n628;
   wire n629;
   wire n630;
   wire n631;
   wire n632;
   wire n633;
   wire n634;
   wire n635;
   wire n636;
   wire n637;
   wire n638;
   wire n639;
   wire n640;
   wire n641;
   wire n642;
   wire n643;
   wire n644;
   wire n645;
   wire n646;
   wire n647;
   wire n648;
   wire n649;
   wire n650;
   wire n651;
   wire n652;
   wire n653;
   wire n654;
   wire n655;
   wire n656;
   wire n657;
   wire n658;
   wire n659;
   wire n660;
   wire n661;
   wire n662;
   wire n663;
   wire n664;
   wire n665;
   wire n666;
   wire n667;
   wire n668;
   wire n669;
   wire n670;
   wire n671;
   wire n672;
   wire n673;
   wire n674;
   wire n675;
   wire n676;
   wire n677;
   wire n678;
   wire n679;
   wire n680;
   wire n681;
   wire n682;
   wire n683;
   wire n684;
   wire n685;
   wire n686;
   wire n687;
   wire n688;
   wire n689;
   wire n690;
   wire n691;
   wire n692;
   wire n693;
   wire n694;
   wire n695;
   wire n696;
   wire n697;
   wire n698;
   wire n699;
   wire n700;
   wire n701;
   wire n702;
   wire n703;
   wire n704;
   wire n705;
   wire n706;
   wire n707;
   wire n708;
   wire n709;
   wire n710;
   wire n711;
   wire n712;
   wire n713;
   wire n714;
   wire n715;
   wire n716;
   wire n717;
   wire n718;
   wire n719;
   wire n720;
   wire n721;
   wire n722;
   wire n723;
   wire n724;
   wire n725;
   wire n726;
   wire n727;
   wire n728;
   wire n729;
   wire n730;
   wire n731;
   wire n732;
   wire n733;
   wire n734;
   wire n735;
   wire n736;
   wire n737;
   wire n738;
   wire n739;
   wire n740;
   wire n741;
   wire n742;
   wire n743;
   wire n744;
   wire n745;
   wire n746;
   wire n747;
   wire n748;
   wire n749;
   wire n750;
   wire n751;
   wire n752;
   wire n753;
   wire n754;
   wire n755;
   wire n756;
   wire n757;
   wire n758;
   wire n759;
   wire n760;
   wire n761;
   wire n762;
   wire n763;
   wire n764;
   wire n765;
   wire n766;
   wire n767;
   wire n768;
   wire n769;
   wire n770;
   wire n771;
   wire n772;
   wire n773;
   wire n774;
   wire n775;
   wire n776;
   wire n777;
   wire n778;
   wire n779;
   wire n780;
   wire n781;
   wire n782;
   wire n783;
   wire n784;
   wire n785;
   wire n786;
   wire n787;
   wire n788;
   wire n789;
   wire n790;
   wire n791;
   wire n792;
   wire n793;
   wire n794;
   wire n795;
   wire n796;
   wire n797;
   wire n798;
   wire n799;
   wire n800;
   wire n801;
   wire n802;
   wire n803;
   wire n804;
   wire n805;
   wire n806;
   wire n807;
   wire n808;
   wire n809;
   wire n810;
   wire n811;
   wire n812;
   wire n813;
   wire n814;
   wire n815;
   wire n816;
   wire n817;
   wire [39:0] \piece_0/feedback ;
   wire [39:0] \piece_1/feedback ;
   wire [17:0] \piece_0/sd_one/sd_reg2 ;
   wire [17:0] \piece_0/sd_one/sd_reg1 ;
   wire [17:0] \piece_1/sd_one/sd_reg2 ;
   wire [17:0] \piece_1/sd_one/sd_reg1 ;

   iid4_b CTS_ccl_a_BUF_clk_G0_L1_2 (.Q(CTS_8),
	.A(clk));
   iid4_b CTS_ccl_a_BUF_clk_G0_L1_1 (.Q(CTS_7),
	.A(clk));
   df001_b \piece_0/sd_one/sd_reg2_reg[0]  (.Q(\piece_0/sd_one/sd_reg2 [0]),
	.C(CTS_8),
	.D(\piece_0/sd_one/N111 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[1]  (.Q(\piece_0/sd_one/sd_reg2 [1]),
	.C(CTS_8),
	.D(\piece_0/sd_one/N112 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[2]  (.Q(\piece_0/sd_one/sd_reg2 [2]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N113 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[3]  (.Q(\piece_0/sd_one/sd_reg2 [3]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N114 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[4]  (.Q(\piece_0/sd_one/sd_reg2 [4]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N115 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[5]  (.Q(\piece_0/sd_one/sd_reg2 [5]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N116 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[6]  (.Q(\piece_0/sd_one/sd_reg2 [6]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N117 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[7]  (.Q(\piece_0/sd_one/sd_reg2 [7]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N118 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[8]  (.Q(\piece_0/sd_one/sd_reg2 [8]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N119 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[9]  (.Q(\piece_0/sd_one/sd_reg2 [9]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N120 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[10]  (.Q(\piece_0/sd_one/sd_reg2 [10]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N121 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[11]  (.Q(\piece_0/sd_one/sd_reg2 [11]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N122 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[12]  (.Q(\piece_0/sd_one/sd_reg2 [12]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N123 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[13]  (.Q(\piece_0/sd_one/sd_reg2 [13]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N124 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[14]  (.Q(\piece_0/sd_one/sd_reg2 [14]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N125 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[15]  (.Q(\piece_0/sd_one/sd_reg2 [15]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N126 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[16]  (.Q(\piece_0/sd_one/sd_reg2 [16]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N127 ));
   df001_b \piece_0/sd_one/sd_reg2_reg[17]  (.Q(\piece_0/sd_one/sd_reg2 [17]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N128 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[0]  (.Q(\piece_0/sd_one/sd_reg1 [0]),
	.C(CTS_8),
	.D(\piece_0/sd_one/N56 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[1]  (.Q(\piece_0/sd_one/sd_reg1 [1]),
	.C(CTS_8),
	.D(\piece_0/sd_one/N57 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[2]  (.Q(\piece_0/sd_one/sd_reg1 [2]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N58 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[3]  (.Q(\piece_0/sd_one/sd_reg1 [3]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N59 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[4]  (.Q(\piece_0/sd_one/sd_reg1 [4]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N60 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[5]  (.Q(\piece_0/sd_one/sd_reg1 [5]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N61 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[6]  (.Q(\piece_0/sd_one/sd_reg1 [6]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N62 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[7]  (.Q(\piece_0/sd_one/sd_reg1 [7]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N63 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[8]  (.Q(\piece_0/sd_one/sd_reg1 [8]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N64 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[9]  (.Q(\piece_0/sd_one/sd_reg1 [9]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N65 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[10]  (.Q(\piece_0/sd_one/sd_reg1 [10]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N66 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[11]  (.Q(\piece_0/sd_one/sd_reg1 [11]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N67 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[12]  (.Q(\piece_0/sd_one/sd_reg1 [12]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N68 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[13]  (.Q(\piece_0/sd_one/sd_reg1 [13]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N69 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[14]  (.Q(\piece_0/sd_one/sd_reg1 [14]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N70 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[15]  (.Q(\piece_0/sd_one/sd_reg1 [15]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N71 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[16]  (.Q(\piece_0/sd_one/sd_reg1 [16]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N72 ));
   df001_b \piece_0/sd_one/sd_reg1_reg[17]  (.Q(\piece_0/sd_one/sd_reg1 [17]),
	.C(CTS_7),
	.D(\piece_0/sd_one/N73 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[0]  (.Q(\piece_1/sd_one/sd_reg2 [0]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N111 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[1]  (.Q(\piece_1/sd_one/sd_reg2 [1]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N112 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[2]  (.Q(\piece_1/sd_one/sd_reg2 [2]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N113 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[3]  (.Q(\piece_1/sd_one/sd_reg2 [3]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N114 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[4]  (.Q(\piece_1/sd_one/sd_reg2 [4]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N115 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[5]  (.Q(\piece_1/sd_one/sd_reg2 [5]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N116 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[6]  (.Q(\piece_1/sd_one/sd_reg2 [6]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N117 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[7]  (.Q(\piece_1/sd_one/sd_reg2 [7]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N118 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[8]  (.Q(\piece_1/sd_one/sd_reg2 [8]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N119 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[9]  (.Q(\piece_1/sd_one/sd_reg2 [9]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N120 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[10]  (.Q(\piece_1/sd_one/sd_reg2 [10]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N121 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[11]  (.Q(\piece_1/sd_one/sd_reg2 [11]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N122 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[12]  (.Q(\piece_1/sd_one/sd_reg2 [12]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N123 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[13]  (.Q(\piece_1/sd_one/sd_reg2 [13]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N124 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[14]  (.Q(\piece_1/sd_one/sd_reg2 [14]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N125 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[15]  (.Q(\piece_1/sd_one/sd_reg2 [15]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N126 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[16]  (.Q(\piece_1/sd_one/sd_reg2 [16]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N127 ));
   df001_b \piece_1/sd_one/sd_reg2_reg[17]  (.Q(\piece_1/sd_one/sd_reg2 [17]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N128 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[0]  (.Q(\piece_1/sd_one/sd_reg1 [0]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N56 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[1]  (.Q(\piece_1/sd_one/sd_reg1 [1]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N57 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[2]  (.Q(\piece_1/sd_one/sd_reg1 [2]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N58 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[3]  (.Q(\piece_1/sd_one/sd_reg1 [3]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N59 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[4]  (.Q(\piece_1/sd_one/sd_reg1 [4]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N60 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[5]  (.Q(\piece_1/sd_one/sd_reg1 [5]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N61 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[6]  (.Q(\piece_1/sd_one/sd_reg1 [6]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N62 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[7]  (.Q(\piece_1/sd_one/sd_reg1 [7]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N63 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[8]  (.Q(\piece_1/sd_one/sd_reg1 [8]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N64 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[9]  (.Q(\piece_1/sd_one/sd_reg1 [9]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N65 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[10]  (.Q(\piece_1/sd_one/sd_reg1 [10]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N66 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[11]  (.Q(\piece_1/sd_one/sd_reg1 [11]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N67 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[12]  (.Q(\piece_1/sd_one/sd_reg1 [12]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N68 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[13]  (.Q(\piece_1/sd_one/sd_reg1 [13]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N69 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[14]  (.Q(\piece_1/sd_one/sd_reg1 [14]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N70 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[15]  (.Q(\piece_1/sd_one/sd_reg1 [15]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N71 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[16]  (.Q(\piece_1/sd_one/sd_reg1 [16]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N72 ));
   df001_b \piece_1/sd_one/sd_reg1_reg[17]  (.Q(\piece_1/sd_one/sd_reg1 [17]),
	.C(CTS_8),
	.D(\piece_1/sd_one/N73 ));
   df001_b \piece_1/feedback_reg[6]  (.Q(\piece_1/feedback [6]),
	.C(CTS_7),
	.D(\piece_1/N16 ));
   df001_b \piece_1/feedback_reg[7]  (.Q(\piece_1/feedback [7]),
	.C(CTS_7),
	.D(\piece_1/N17 ));
   df001_b \piece_1/feedback_reg[8]  (.Q(\piece_1/feedback [8]),
	.C(CTS_7),
	.D(\piece_1/N18 ));
   df001_b \piece_1/feedback_reg[9]  (.Q(\piece_1/feedback [9]),
	.C(CTS_7),
	.D(\piece_1/N19 ));
   df001_b \piece_1/feedback_reg[10]  (.Q(\piece_1/feedback [10]),
	.C(CTS_7),
	.D(\piece_1/N20 ));
   df001_b \piece_1/feedback_reg[11]  (.Q(\piece_1/feedback [11]),
	.C(CTS_7),
	.D(\piece_1/N21 ));
   df001_b \piece_1/feedback_reg[12]  (.Q(\piece_1/feedback [12]),
	.C(CTS_7),
	.D(\piece_1/N22 ));
   df001_b \piece_1/feedback_reg[13]  (.Q(\piece_1/feedback [13]),
	.C(CTS_7),
	.D(\piece_1/N23 ));
   df001_b \piece_1/feedback_reg[14]  (.Q(\piece_1/feedback [14]),
	.C(CTS_7),
	.D(\piece_1/N24 ));
   df001_b \piece_1/feedback_reg[15]  (.Q(\piece_1/feedback [15]),
	.C(CTS_7),
	.D(\piece_1/N25 ));
   df001_b \piece_1/feedback_reg[16]  (.Q(\piece_1/feedback [16]),
	.C(CTS_7),
	.D(\piece_1/N26 ));
   df001_b \piece_1/feedback_reg[17]  (.Q(\piece_1/feedback [17]),
	.C(CTS_7),
	.D(\piece_1/N27 ));
   df001_b \piece_1/feedback_reg[18]  (.Q(\piece_1/feedback [18]),
	.C(CTS_7),
	.D(\piece_1/N28 ));
   df001_b \piece_1/feedback_reg[19]  (.Q(\piece_1/feedback [19]),
	.C(CTS_7),
	.D(\piece_1/N29 ));
   df001_b \piece_1/feedback_reg[20]  (.Q(\piece_1/feedback [20]),
	.C(CTS_7),
	.D(\piece_1/N30 ));
   df001_b \piece_1/feedback_reg[21]  (.Q(\piece_1/feedback [21]),
	.C(CTS_7),
	.D(\piece_1/N31 ));
   df001_b \piece_1/feedback_reg[22]  (.Q(\piece_1/feedback [22]),
	.C(CTS_8),
	.D(\piece_1/N32 ));
   df001_b \piece_1/feedback_reg[23]  (.Q(\piece_1/feedback [23]),
	.C(CTS_8),
	.D(\piece_1/N33 ));
   df001_b \piece_1/feedback_reg[24]  (.Q(\piece_1/feedback [24]),
	.C(CTS_8),
	.D(\piece_1/N34 ));
   df001_b \piece_1/feedback_reg[25]  (.Q(\piece_1/feedback [25]),
	.C(CTS_7),
	.D(\piece_1/N35 ));
   df001_b \piece_1/feedback_reg[26]  (.Q(\piece_1/feedback [26]),
	.C(CTS_8),
	.D(\piece_1/N36 ));
   df001_b \piece_1/feedback_reg[27]  (.Q(\piece_1/feedback [27]),
	.C(CTS_8),
	.D(\piece_1/N37 ));
   df001_b \piece_1/feedback_reg[28]  (.Q(\piece_1/feedback [28]),
	.C(CTS_8),
	.D(\piece_1/N38 ));
   df001_b \piece_1/feedback_reg[29]  (.Q(\piece_1/feedback [29]),
	.C(CTS_8),
	.D(\piece_1/N39 ));
   df001_b \piece_1/feedback_reg[30]  (.Q(\piece_1/feedback [30]),
	.C(CTS_8),
	.D(\piece_1/N40 ));
   df001_b \piece_1/feedback_reg[31]  (.Q(\piece_1/feedback [31]),
	.C(CTS_8),
	.D(\piece_1/N41 ));
   df001_b \piece_1/feedback_reg[32]  (.Q(\piece_1/feedback [32]),
	.C(CTS_8),
	.D(\piece_1/N42 ));
   df001_b \piece_1/feedback_reg[33]  (.Q(\piece_1/feedback [33]),
	.C(CTS_8),
	.D(\piece_1/N43 ));
   df001_b \piece_1/feedback_reg[34]  (.Q(\piece_1/feedback [34]),
	.C(CTS_8),
	.D(\piece_1/N44 ));
   df001_b \piece_1/feedback_reg[35]  (.Q(\piece_1/feedback [35]),
	.C(CTS_8),
	.D(\piece_1/N45 ));
   df001_b \piece_1/feedback_reg[36]  (.Q(\piece_1/feedback [36]),
	.C(CTS_8),
	.D(\piece_1/N46 ));
   df001_b \piece_1/feedback_reg[37]  (.Q(\piece_1/feedback [37]),
	.C(CTS_8),
	.D(\piece_1/N47 ));
   df001_b \piece_1/feedback_reg[38]  (.Q(\piece_1/feedback [38]),
	.C(CTS_8),
	.D(\piece_1/N48 ));
   df001_b \piece_1/feedback_reg[39]  (.Q(\piece_1/feedback [39]),
	.C(CTS_8),
	.D(\piece_1/N49 ));
   df001_b \piece_0/feedback_reg[6]  (.Q(\piece_0/feedback [6]),
	.C(CTS_8),
	.D(\piece_0/N16 ));
   df001_b \piece_0/feedback_reg[7]  (.Q(\piece_0/feedback [7]),
	.C(CTS_8),
	.D(\piece_0/N17 ));
   df001_b \piece_0/feedback_reg[8]  (.Q(\piece_0/feedback [8]),
	.C(CTS_8),
	.D(\piece_0/N18 ));
   df001_b \piece_0/feedback_reg[9]  (.Q(\piece_0/feedback [9]),
	.C(CTS_8),
	.D(\piece_0/N19 ));
   df001_b \piece_0/feedback_reg[10]  (.Q(\piece_0/feedback [10]),
	.C(CTS_8),
	.D(\piece_0/N20 ));
   df001_b \piece_0/feedback_reg[11]  (.Q(\piece_0/feedback [11]),
	.C(CTS_8),
	.D(\piece_0/N21 ));
   df001_b \piece_0/feedback_reg[12]  (.Q(\piece_0/feedback [12]),
	.C(CTS_8),
	.D(\piece_0/N22 ));
   df001_b \piece_0/feedback_reg[13]  (.Q(\piece_0/feedback [13]),
	.C(CTS_8),
	.D(\piece_0/N23 ));
   df001_b \piece_0/feedback_reg[14]  (.Q(\piece_0/feedback [14]),
	.C(CTS_8),
	.D(\piece_0/N24 ));
   df001_b \piece_0/feedback_reg[15]  (.Q(\piece_0/feedback [15]),
	.C(CTS_8),
	.D(\piece_0/N25 ));
   df001_b \piece_0/feedback_reg[16]  (.Q(\piece_0/feedback [16]),
	.C(CTS_8),
	.D(\piece_0/N26 ));
   df001_b \piece_0/feedback_reg[17]  (.Q(\piece_0/feedback [17]),
	.C(CTS_7),
	.D(\piece_0/N27 ));
   df001_b \piece_0/feedback_reg[18]  (.Q(\piece_0/feedback [18]),
	.C(CTS_7),
	.D(\piece_0/N28 ));
   df001_b \piece_0/feedback_reg[19]  (.Q(\piece_0/feedback [19]),
	.C(CTS_7),
	.D(\piece_0/N29 ));
   df001_b \piece_0/feedback_reg[20]  (.Q(\piece_0/feedback [20]),
	.C(CTS_7),
	.D(\piece_0/N30 ));
   df001_b \piece_0/feedback_reg[21]  (.Q(\piece_0/feedback [21]),
	.C(CTS_7),
	.D(\piece_0/N31 ));
   df001_b \piece_0/feedback_reg[22]  (.Q(\piece_0/feedback [22]),
	.C(CTS_7),
	.D(\piece_0/N32 ));
   df001_b \piece_0/feedback_reg[23]  (.Q(\piece_0/feedback [23]),
	.C(CTS_7),
	.D(\piece_0/N33 ));
   df001_b \piece_0/feedback_reg[24]  (.Q(\piece_0/feedback [24]),
	.C(CTS_7),
	.D(\piece_0/N34 ));
   df001_b \piece_0/feedback_reg[25]  (.Q(\piece_0/feedback [25]),
	.C(CTS_8),
	.D(\piece_0/N35 ));
   df001_b \piece_0/feedback_reg[26]  (.Q(\piece_0/feedback [26]),
	.C(CTS_8),
	.D(\piece_0/N36 ));
   df001_b \piece_0/feedback_reg[27]  (.Q(\piece_0/feedback [27]),
	.C(CTS_7),
	.D(\piece_0/N37 ));
   df001_b \piece_0/feedback_reg[28]  (.Q(\piece_0/feedback [28]),
	.C(CTS_7),
	.D(\piece_0/N38 ));
   df001_b \piece_0/feedback_reg[29]  (.Q(\piece_0/feedback [29]),
	.C(CTS_7),
	.D(\piece_0/N39 ));
   df001_b \piece_0/feedback_reg[30]  (.Q(\piece_0/feedback [30]),
	.C(CTS_7),
	.D(\piece_0/N40 ));
   df001_b \piece_0/feedback_reg[31]  (.Q(\piece_0/feedback [31]),
	.C(CTS_7),
	.D(\piece_0/N41 ));
   df001_b \piece_0/feedback_reg[32]  (.Q(\piece_0/feedback [32]),
	.C(CTS_7),
	.D(\piece_0/N42 ));
   df001_b \piece_0/feedback_reg[33]  (.Q(\piece_0/feedback [33]),
	.C(CTS_7),
	.D(\piece_0/N43 ));
   df001_b \piece_0/feedback_reg[34]  (.Q(\piece_0/feedback [34]),
	.C(CTS_7),
	.D(\piece_0/N44 ));
   df001_b \piece_0/feedback_reg[35]  (.Q(\piece_0/feedback [35]),
	.C(CTS_7),
	.D(\piece_0/N45 ));
   df001_b \piece_0/feedback_reg[36]  (.Q(\piece_0/feedback [36]),
	.C(CTS_7),
	.D(\piece_0/N46 ));
   df001_b \piece_0/feedback_reg[37]  (.Q(\piece_0/feedback [37]),
	.C(CTS_7),
	.D(\piece_0/N47 ));
   df001_b \piece_0/feedback_reg[38]  (.Q(\piece_0/feedback [38]),
	.C(CTS_7),
	.D(\piece_0/N48 ));
   df001_b \piece_0/feedback_reg[39]  (.Q(\piece_0/feedback [39]),
	.C(CTS_7),
	.D(\piece_0/N49 ));
   aa21_b U269 (.Q(n102),
	.A(n686),
	.B(n798));
   inv1_b U270 (.Q(n554),
	.A(n555));
   inv1_b U271 (.Q(n139),
	.A(n129));
   inv1_b U272 (.Q(n118),
	.A(n723));
   inv1_b U273 (.Q(n142),
	.A(n128));
   inv1_b U274 (.Q(n722),
	.A(n102));
   inv1_b U275 (.Q(n621),
	.A(n557));
   aa21_b U276 (.Q(n267),
	.A(\piece_1/feedback [24]),
	.B(\piece_1/sd_one/sd_reg2 [0]));
   inv1_b U277 (.Q(n814),
	.A(n811));
   inv1_b U278 (.Q(n791),
	.A(n793));
   inv1_b U279 (.Q(n757),
	.A(n755));
   inv1_b U280 (.Q(n809),
	.A(n802));
   inv1_b U281 (.Q(n528),
	.A(n526));
   inv1_b U282 (.Q(n512),
	.A(n322));
   inv1_b U283 (.Q(n472),
	.A(n272));
   inv1_b U284 (.Q(n449),
	.A(n447));
   inv1_b U285 (.Q(n425),
	.A(n196));
   inv1_b U286 (.Q(n448),
	.A(n450));
   inv1_b U287 (.Q(n682),
	.A(reset));
   inv1_b U288 (.Q(n817),
	.A(n725));
   inv1_b U289 (.Q(n639),
	.A(n617));
   inv1_b U290 (.Q(n798),
	.A(n806));
   inv1_b U291 (.Q(n332),
	.A(n462));
   inv1_b U292 (.Q(n500),
	.A(n308));
   inv1_b U293 (.Q(n484),
	.A(n288));
   inv1_b U294 (.Q(n464),
	.A(n460));
   inv1_b U295 (.Q(n636),
	.A(n634));
   inv1_b U296 (.Q(n217),
	.A(n214));
   inv1_b U297 (.Q(n421),
	.A(n192));
   inv1_b U298 (.Q(n397),
	.A(n162));
   na21_b U299 (.Q(n806),
	.A(n682),
	.B(sd_out[1]));
   inv1_b U300 (.Q(n103),
	.A(\piece_0/feedback [39]));
   on11_b U301 (.Q(n148),
	.A(\piece_0/feedback [39]),
	.B(n806),
	.C(n103),
	.D(n798));
   na21_b U302 (.Q(n747),
	.A(n682),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   aa21_b U303 (.Q(n717),
	.A(n603),
	.B(\piece_0/feedback [19]));
   na21_b U304 (.Q(n616),
	.A(n682),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   inv1_b U305 (.Q(n713),
	.A(n616));
   no21_b U306 (.Q(n115),
	.A(\piece_0/feedback [17]),
	.B(sd_out[0]));
   inv1_b U307 (.Q(n707),
	.A(\piece_0/feedback [16]));
   on21_b U308 (.Q(n104),
	.A(n603),
	.B(\piece_0/feedback [6]),
	.C(\piece_0/feedback [7]));
   inv1_b U309 (.Q(n687),
	.A(\piece_0/feedback [6]));
   on21_b U310 (.Q(n690),
	.A(n687),
	.B(n747),
	.C(n104));
   on21_b U311 (.Q(n105),
	.A(n798),
	.B(n690),
	.C(\piece_0/feedback [8]));
   on21_b U312 (.Q(n692),
	.A(n104),
	.B(n806),
	.C(n105));
   on21_b U313 (.Q(n106),
	.A(n603),
	.B(n692),
	.C(\piece_0/feedback [9]));
   on21_b U314 (.Q(n694),
	.A(n105),
	.B(n747),
	.C(n106));
   on21_b U315 (.Q(n108),
	.A(n798),
	.B(n694),
	.C(\piece_0/feedback [10]));
   on21_b U316 (.Q(n696),
	.A(n106),
	.B(n806),
	.C(n108));
   inv1_b U317 (.Q(n107),
	.A(\piece_0/feedback [11]));
   an21_b U318 (.Q(n109),
	.A(n806),
	.B(n108),
	.C(n107));
   an21_b U319 (.Q(n698),
	.A(n798),
	.B(n696),
	.C(n109));
   on21_b U320 (.Q(n112),
	.A(n798),
	.B(n109),
	.C(\piece_0/feedback [12]));
   on21_b U321 (.Q(n700),
	.A(n698),
	.B(n806),
	.C(n112));
   on21_b U322 (.Q(n111),
	.A(n603),
	.B(n700),
	.C(\piece_0/feedback [13]));
   inv1_b U323 (.Q(n110),
	.A(\piece_0/feedback [14]));
   an21_b U324 (.Q(n114),
	.A(n747),
	.B(n111),
	.C(n110));
   on21_b U325 (.Q(n702),
	.A(n112),
	.B(n747),
	.C(n111));
   an21_b U326 (.Q(n704),
	.A(n603),
	.B(n702),
	.C(n114));
   no21_b U327 (.Q(n113),
	.A(n704),
	.B(n747));
   on11_b U328 (.Q(n706),
	.A(n603),
	.B(n114),
	.C(n113),
	.D(\piece_0/feedback [15]));
   na21_b U329 (.Q(n709),
	.A(\piece_0/feedback [17]),
	.B(sd_out[0]));
   on21_b U330 (.Q(n715),
	.A(n115),
	.B(n711),
	.C(n709));
   on21_b U331 (.Q(n117),
	.A(n713),
	.B(n715),
	.C(\piece_0/feedback [18]));
   na21_b U332 (.Q(n116),
	.A(n713),
	.B(n715));
   na21_b U333 (.Q(n720),
	.A(n117),
	.B(n116));
   on11_b U334 (.Q(n723),
	.A(n717),
	.B(n720),
	.C(n603),
	.D(\piece_0/feedback [19]));
   on21_b U335 (.Q(n120),
	.A(n798),
	.B(n118),
	.C(\piece_0/feedback [20]));
   na21_b U336 (.Q(n119),
	.A(n798),
	.B(n118));
   na21_b U337 (.Q(n727),
	.A(n120),
	.B(n119));
   on21_b U338 (.Q(n731),
	.A(n603),
	.B(n727),
	.C(\piece_0/feedback [21]));
   on21_b U339 (.Q(n730),
	.A(n120),
	.B(n747),
	.C(n731));
   on21_b U340 (.Q(n122),
	.A(n798),
	.B(n730),
	.C(\piece_0/feedback [22]));
   inv1_b U341 (.Q(n741),
	.A(\piece_0/feedback [23]));
   an21_b U342 (.Q(n121),
	.A(n806),
	.B(n122),
	.C(n741));
   on21_b U343 (.Q(n125),
	.A(n798),
	.B(n121),
	.C(\piece_0/feedback [24]));
   inv1_b U344 (.Q(n123),
	.A(n121));
   or21_b U345 (.Q(n729),
	.A(n806),
	.B(n731));
   na21_b U346 (.Q(n738),
	.A(n122),
	.B(n729));
   na21_b U347 (.Q(n737),
	.A(n798),
	.B(n738));
   na21_b U348 (.Q(n742),
	.A(n123),
	.B(n737));
   na21_b U349 (.Q(n124),
	.A(n798),
	.B(n742));
   na21_b U350 (.Q(n745),
	.A(n125),
	.B(n124));
   on21_b U351 (.Q(n126),
	.A(n603),
	.B(n745),
	.C(\piece_0/feedback [25]));
   on21_b U352 (.Q(n749),
	.A(n125),
	.B(n747),
	.C(n126));
   inv1_b U353 (.Q(n748),
	.A(\piece_0/feedback [26]));
   an21_b U354 (.Q(n127),
	.A(n747),
	.B(n126),
	.C(n748));
   an21_b U355 (.Q(n752),
	.A(n603),
	.B(n749),
	.C(n127));
   on21_b U356 (.Q(n756),
	.A(n603),
	.B(n127),
	.C(\piece_0/feedback [27]));
   on21_b U357 (.Q(n755),
	.A(n752),
	.B(n747),
	.C(n756));
   on21_b U358 (.Q(n132),
	.A(n798),
	.B(n755),
	.C(\piece_0/feedback [28]));
   inv1_b U359 (.Q(n766),
	.A(\piece_0/feedback [29]));
   an21_b U360 (.Q(n131),
	.A(n806),
	.B(n132),
	.C(n766));
   on21_b U361 (.Q(n135),
	.A(n798),
	.B(n131),
	.C(\piece_0/feedback [30]));
   inv1_b U362 (.Q(n776),
	.A(\piece_0/feedback [31]));
   an21_b U363 (.Q(n130),
	.A(n806),
	.B(n135),
	.C(n776));
   on21_b U364 (.Q(n138),
	.A(n798),
	.B(n130),
	.C(\piece_0/feedback [32]));
   inv1_b U365 (.Q(n786),
	.A(\piece_0/feedback [33]));
   an21_b U366 (.Q(n129),
	.A(n806),
	.B(n138),
	.C(n786));
   on21_b U367 (.Q(n141),
	.A(n798),
	.B(n129),
	.C(\piece_0/feedback [34]));
   inv1_b U368 (.Q(n796),
	.A(\piece_0/feedback [35]));
   an21_b U369 (.Q(n128),
	.A(n806),
	.B(n141),
	.C(n796));
   on21_b U370 (.Q(n144),
	.A(n798),
	.B(n128),
	.C(\piece_0/feedback [36]));
   inv1_b U371 (.Q(n801),
	.A(\piece_0/feedback [37]));
   no21_b U372 (.Q(n810),
	.A(n144),
	.B(n801));
   on21_b U373 (.Q(n813),
	.A(n798),
	.B(n810),
	.C(\piece_0/feedback [38]));
   inv1_b U374 (.Q(n136),
	.A(n130));
   inv1_b U375 (.Q(n133),
	.A(n131));
   or21_b U376 (.Q(n754),
	.A(n806),
	.B(n756));
   na21_b U377 (.Q(n763),
	.A(n132),
	.B(n754));
   na21_b U378 (.Q(n762),
	.A(n798),
	.B(n763));
   na21_b U379 (.Q(n769),
	.A(n133),
	.B(n762));
   na21_b U380 (.Q(n134),
	.A(n798),
	.B(n769));
   na21_b U381 (.Q(n773),
	.A(n135),
	.B(n134));
   na21_b U382 (.Q(n772),
	.A(n798),
	.B(n773));
   na21_b U383 (.Q(n779),
	.A(n136),
	.B(n772));
   na21_b U384 (.Q(n137),
	.A(n798),
	.B(n779));
   na21_b U385 (.Q(n783),
	.A(n138),
	.B(n137));
   na21_b U386 (.Q(n782),
	.A(n798),
	.B(n783));
   na21_b U387 (.Q(n789),
	.A(n139),
	.B(n782));
   na21_b U388 (.Q(n140),
	.A(n798),
	.B(n789));
   na21_b U389 (.Q(n793),
	.A(n141),
	.B(n140));
   na21_b U390 (.Q(n792),
	.A(n798),
	.B(n793));
   na21_b U391 (.Q(n805),
	.A(n142),
	.B(n792));
   na21_b U392 (.Q(n143),
	.A(n798),
	.B(n805));
   na21_b U393 (.Q(n803),
	.A(n144),
	.B(n143));
   on21_b U394 (.Q(n811),
	.A(\piece_0/feedback [37]),
	.B(n803),
	.C(n798));
   na21_b U395 (.Q(n147),
	.A(n813),
	.B(n811));
   inv1_b U396 (.Q(sd_out[1]),
	.A(\piece_1/sd_one/sd_reg1 [17]));
   no21_b U397 (.Q(n686),
	.A(n148),
	.B(n147));
   or21_b U398 (.Q(n145),
	.A(\piece_0/feedback [39]),
	.B(n686));
   on21_b U399 (.Q(n725),
	.A(sd_out[1]),
	.B(n145),
	.C(n682));
   on21_b U400 (.Q(n146),
	.A(\piece_0/feedback [39]),
	.B(n148),
	.C(n817));
   an21_b U401 (.Q(\piece_0/N49 ),
	.A(n148),
	.B(n147),
	.C(n146));
   aa21_b U402 (.Q(n151),
	.A(\piece_0/feedback [24]),
	.B(\piece_0/sd_one/sd_reg2 [0]));
   inv1_b U403 (.Q(n387),
	.A(n152));
   eo21_b U404 (.Q(n385),
	.A(\piece_0/feedback [24]),
	.B(\piece_0/sd_one/sd_reg2 [0]));
   na21_b U405 (.Q(n150),
	.A(n385),
	.B(sd_out[0]));
   on21_b U406 (.Q(n149),
	.A(n387),
	.B(n150),
	.C(n682));
   an21_b U407 (.Q(\piece_0/sd_one/N112 ),
	.A(n387),
	.B(n150),
	.C(n149));
   au11_b U408 (.CO(n155),
	.S(n152),
	.A(\piece_0/sd_one/sd_reg2 [1]),
	.B(\piece_0/feedback [25]),
	.CI(n151));
   na21_b U409 (.Q(n157),
	.A(n152),
	.B(n385));
   no21_b U410 (.Q(n154),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n157));
   on21_b U411 (.Q(n153),
	.A(n156),
	.B(n154),
	.C(n682));
   an21_b U412 (.Q(\piece_0/sd_one/N113 ),
	.A(n156),
	.B(n154),
	.C(n153));
   au11_b U413 (.CO(n160),
	.S(n156),
	.A(\piece_0/sd_one/sd_reg2 [2]),
	.B(\piece_0/feedback [26]),
	.CI(n155));
   inv1_b U414 (.Q(n393),
	.A(n156));
   no21_b U415 (.Q(n161),
	.A(n157),
	.B(n393));
   na21_b U416 (.Q(n159),
	.A(n161),
	.B(sd_out[0]));
   on21_b U417 (.Q(n158),
	.A(n397),
	.B(n159),
	.C(n682));
   an21_b U418 (.Q(\piece_0/sd_one/N114 ),
	.A(n397),
	.B(n159),
	.C(n158));
   au11_b U419 (.CO(n165),
	.S(n162),
	.A(\piece_0/sd_one/sd_reg2 [3]),
	.B(\piece_0/feedback [27]),
	.CI(n160));
   na21_b U420 (.Q(n167),
	.A(n162),
	.B(n161));
   no21_b U421 (.Q(n164),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n167));
   on21_b U422 (.Q(n163),
	.A(n166),
	.B(n164),
	.C(n682));
   an21_b U423 (.Q(\piece_0/sd_one/N115 ),
	.A(n166),
	.B(n164),
	.C(n163));
   au11_b U424 (.CO(n170),
	.S(n166),
	.A(\piece_0/sd_one/sd_reg2 [4]),
	.B(\piece_0/feedback [28]),
	.CI(n165));
   inv1_b U425 (.Q(n405),
	.A(n172));
   inv1_b U426 (.Q(n401),
	.A(n166));
   no21_b U427 (.Q(n171),
	.A(n167),
	.B(n401));
   na21_b U428 (.Q(n169),
	.A(n171),
	.B(sd_out[0]));
   on21_b U429 (.Q(n168),
	.A(n405),
	.B(n169),
	.C(n682));
   an21_b U430 (.Q(\piece_0/sd_one/N116 ),
	.A(n405),
	.B(n169),
	.C(n168));
   au11_b U431 (.CO(n175),
	.S(n172),
	.A(\piece_0/sd_one/sd_reg2 [5]),
	.B(\piece_0/feedback [29]),
	.CI(n170));
   na21_b U432 (.Q(n177),
	.A(n172),
	.B(n171));
   no21_b U433 (.Q(n174),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n177));
   on21_b U434 (.Q(n173),
	.A(n176),
	.B(n174),
	.C(n682));
   an21_b U435 (.Q(\piece_0/sd_one/N117 ),
	.A(n176),
	.B(n174),
	.C(n173));
   au11_b U436 (.CO(n180),
	.S(n176),
	.A(\piece_0/sd_one/sd_reg2 [6]),
	.B(\piece_0/feedback [30]),
	.CI(n175));
   inv1_b U437 (.Q(n413),
	.A(n182));
   inv1_b U438 (.Q(n409),
	.A(n176));
   no21_b U439 (.Q(n181),
	.A(n177),
	.B(n409));
   na21_b U440 (.Q(n179),
	.A(n181),
	.B(sd_out[0]));
   on21_b U441 (.Q(n178),
	.A(n413),
	.B(n179),
	.C(n682));
   an21_b U442 (.Q(\piece_0/sd_one/N118 ),
	.A(n413),
	.B(n179),
	.C(n178));
   au11_b U443 (.CO(n185),
	.S(n182),
	.A(\piece_0/sd_one/sd_reg2 [7]),
	.B(\piece_0/feedback [31]),
	.CI(n180));
   na21_b U444 (.Q(n187),
	.A(n182),
	.B(n181));
   no21_b U445 (.Q(n184),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n187));
   on21_b U446 (.Q(n183),
	.A(n186),
	.B(n184),
	.C(n682));
   an21_b U447 (.Q(\piece_0/sd_one/N119 ),
	.A(n186),
	.B(n184),
	.C(n183));
   au11_b U448 (.CO(n190),
	.S(n186),
	.A(\piece_0/sd_one/sd_reg2 [8]),
	.B(\piece_0/feedback [32]),
	.CI(n185));
   inv1_b U449 (.Q(n417),
	.A(n186));
   no21_b U450 (.Q(n191),
	.A(n187),
	.B(n417));
   na21_b U451 (.Q(n189),
	.A(n191),
	.B(sd_out[0]));
   on21_b U452 (.Q(n188),
	.A(n421),
	.B(n189),
	.C(n682));
   an21_b U453 (.Q(\piece_0/sd_one/N120 ),
	.A(n421),
	.B(n189),
	.C(n188));
   au11_b U454 (.CO(n195),
	.S(n192),
	.A(\piece_0/sd_one/sd_reg2 [9]),
	.B(\piece_0/feedback [33]),
	.CI(n190));
   na21_b U455 (.Q(n197),
	.A(n192),
	.B(n191));
   no21_b U456 (.Q(n194),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n197));
   on21_b U457 (.Q(n193),
	.A(n196),
	.B(n194),
	.C(n682));
   an21_b U458 (.Q(\piece_0/sd_one/N121 ),
	.A(n196),
	.B(n194),
	.C(n193));
   au11_b U459 (.CO(n200),
	.S(n196),
	.A(\piece_0/sd_one/sd_reg2 [10]),
	.B(\piece_0/feedback [34]),
	.CI(n195));
   inv1_b U460 (.Q(n429),
	.A(n202));
   no21_b U461 (.Q(n201),
	.A(n197),
	.B(n425));
   na21_b U462 (.Q(n199),
	.A(n201),
	.B(sd_out[0]));
   on21_b U463 (.Q(n198),
	.A(n429),
	.B(n199),
	.C(n682));
   an21_b U464 (.Q(\piece_0/sd_one/N122 ),
	.A(n429),
	.B(n199),
	.C(n198));
   au11_b U465 (.CO(n205),
	.S(n202),
	.A(\piece_0/sd_one/sd_reg2 [11]),
	.B(\piece_0/feedback [35]),
	.CI(n200));
   na21_b U466 (.Q(n207),
	.A(n202),
	.B(n201));
   no21_b U467 (.Q(n204),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n207));
   on21_b U468 (.Q(n203),
	.A(n206),
	.B(n204),
	.C(n682));
   an21_b U469 (.Q(\piece_0/sd_one/N123 ),
	.A(n206),
	.B(n204),
	.C(n203));
   au11_b U470 (.CO(n210),
	.S(n206),
	.A(\piece_0/sd_one/sd_reg2 [12]),
	.B(\piece_0/feedback [36]),
	.CI(n205));
   inv1_b U471 (.Q(n437),
	.A(n212));
   inv1_b U472 (.Q(n433),
	.A(n206));
   no21_b U473 (.Q(n211),
	.A(n207),
	.B(n433));
   na21_b U474 (.Q(n209),
	.A(n211),
	.B(sd_out[0]));
   on21_b U475 (.Q(n208),
	.A(n437),
	.B(n209),
	.C(n682));
   an21_b U476 (.Q(\piece_0/sd_one/N124 ),
	.A(n437),
	.B(n209),
	.C(n208));
   au11_b U477 (.CO(n218),
	.S(n212),
	.A(\piece_0/sd_one/sd_reg2 [13]),
	.B(\piece_0/feedback [37]),
	.CI(n210));
   inv1_b U478 (.Q(n441),
	.A(n215));
   na21_b U479 (.Q(n213),
	.A(n212),
	.B(n211));
   no21_b U480 (.Q(n214),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n213));
   na21_b U481 (.Q(n383),
	.A(n215),
	.B(n214));
   inv1_b U482 (.Q(n216),
	.A(n383));
   an31_b U483 (.Q(\piece_0/sd_one/N125 ),
	.A(n441),
	.B(n217),
	.C(reset),
	.D(n216));
   na21_b U484 (.Q(n634),
	.A(n682),
	.B(sd_out[0]));
   au11_b U485 (.CO(n220),
	.S(n215),
	.A(\piece_0/sd_one/sd_reg2 [14]),
	.B(\piece_0/feedback [38]),
	.CI(n218));
   inv1_b U486 (.Q(n445),
	.A(n219));
   na21_b U487 (.Q(n382),
	.A(n445),
	.B(n383));
   au11_b U488 (.CO(n223),
	.S(n219),
	.A(\piece_0/sd_one/sd_reg2 [15]),
	.B(\piece_0/feedback [39]),
	.CI(n220));
   eo21_b U489 (.Q(n221),
	.A(n382),
	.B(n448));
   mx21_b U490 (.Q(\piece_0/sd_one/N127 ),
	.I0(n713),
	.I1(n636),
	.S(n221));
   inv1_b U491 (.Q(sd_out[0]),
	.A(\piece_0/sd_one/sd_reg1 [17]));
   aa21_b U492 (.Q(n222),
	.A(sd_out[0]),
	.B(n382));
   on11_b U493 (.Q(n225),
	.A(sd_out[0]),
	.B(n382),
	.C(n450),
	.D(n222));
   au11_b U494 (.CO(n224),
	.S(n450),
	.A(\piece_0/sd_one/sd_reg2 [16]),
	.B(\piece_0/feedback [39]),
	.CI(n223));
   eo31_b U495 (.Q(n455),
	.A(\piece_0/feedback [39]),
	.B(\piece_0/sd_one/sd_reg2 [17]),
	.C(n224));
   eo21_b U496 (.Q(n226),
	.A(n225),
	.B(n455));
   mx21_b U497 (.Q(\piece_0/sd_one/N128 ),
	.I0(n713),
	.I1(n636),
	.S(n226));
   na21_b U498 (.Q(n235),
	.A(\piece_0/sd_one/sd_reg1 [16]),
	.B(sd_out[0]));
   on21_b U499 (.Q(n234),
	.A(\piece_0/sd_one/sd_reg1 [16]),
	.B(sd_out[0]),
	.C(n235));
   na21_b U500 (.Q(n237),
	.A(\piece_0/sd_one/sd_reg1 [2]),
	.B(\piece_0/sd_one/sd_reg1 [1]));
   inv1_b U501 (.Q(n227),
	.A(\piece_0/sd_one/sd_reg1 [3]));
   no21_b U502 (.Q(n239),
	.A(n237),
	.B(n227));
   na21_b U503 (.Q(n241),
	.A(\piece_0/sd_one/sd_reg1 [4]),
	.B(n239));
   inv1_b U504 (.Q(n228),
	.A(\piece_0/sd_one/sd_reg1 [5]));
   no21_b U505 (.Q(n243),
	.A(n241),
	.B(n228));
   na21_b U506 (.Q(n245),
	.A(\piece_0/sd_one/sd_reg1 [6]),
	.B(n243));
   inv1_b U507 (.Q(n229),
	.A(\piece_0/sd_one/sd_reg1 [7]));
   no21_b U508 (.Q(n247),
	.A(n245),
	.B(n229));
   na21_b U509 (.Q(n249),
	.A(\piece_0/sd_one/sd_reg1 [8]),
	.B(n247));
   inv1_b U510 (.Q(n230),
	.A(\piece_0/sd_one/sd_reg1 [9]));
   no21_b U511 (.Q(n251),
	.A(n249),
	.B(n230));
   na21_b U512 (.Q(n253),
	.A(\piece_0/sd_one/sd_reg1 [10]),
	.B(n251));
   inv1_b U513 (.Q(n231),
	.A(\piece_0/sd_one/sd_reg1 [11]));
   no21_b U514 (.Q(n255),
	.A(n253),
	.B(n231));
   na21_b U515 (.Q(n257),
	.A(\piece_0/sd_one/sd_reg1 [12]),
	.B(n255));
   inv1_b U516 (.Q(n232),
	.A(\piece_0/sd_one/sd_reg1 [13]));
   no21_b U517 (.Q(n259),
	.A(n257),
	.B(n232));
   na21_b U518 (.Q(n261),
	.A(\piece_0/sd_one/sd_reg1 [14]),
	.B(n259));
   inv1_b U519 (.Q(n233),
	.A(\piece_0/sd_one/sd_reg1 [15]));
   on21_b U520 (.Q(n454),
	.A(n261),
	.B(n233),
	.C(sd_out[0]));
   mx21_b U521 (.Q(n451),
	.I0(n235),
	.I1(n234),
	.S(n454));
   en21_b U522 (.Q(n389),
	.A(\piece_0/sd_one/sd_reg1 [1]),
	.B(sd_out[0]));
   na21_b U523 (.Q(n388),
	.A(n385),
	.B(\piece_0/sd_one/sd_reg1 [0]));
   na21_b U524 (.Q(n236),
	.A(sd_out[0]),
	.B(\piece_0/sd_one/sd_reg1 [1]));
   eo21_b U525 (.Q(n391),
	.A(n236),
	.B(\piece_0/sd_one/sd_reg1 [2]));
   no21_b U526 (.Q(n238),
	.A(n237),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U527 (.Q(n395),
	.A(n238),
	.B(\piece_0/sd_one/sd_reg1 [3]));
   na21_b U528 (.Q(n240),
	.A(sd_out[0]),
	.B(n239));
   eo21_b U529 (.Q(n399),
	.A(n240),
	.B(\piece_0/sd_one/sd_reg1 [4]));
   no21_b U530 (.Q(n242),
	.A(n241),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U531 (.Q(n403),
	.A(n242),
	.B(\piece_0/sd_one/sd_reg1 [5]));
   na21_b U532 (.Q(n244),
	.A(sd_out[0]),
	.B(n243));
   eo21_b U533 (.Q(n407),
	.A(n244),
	.B(\piece_0/sd_one/sd_reg1 [6]));
   no21_b U534 (.Q(n246),
	.A(n245),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U535 (.Q(n411),
	.A(n246),
	.B(\piece_0/sd_one/sd_reg1 [7]));
   na21_b U536 (.Q(n248),
	.A(sd_out[0]),
	.B(n247));
   eo21_b U537 (.Q(n415),
	.A(n248),
	.B(\piece_0/sd_one/sd_reg1 [8]));
   no21_b U538 (.Q(n250),
	.A(n249),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U539 (.Q(n419),
	.A(n250),
	.B(\piece_0/sd_one/sd_reg1 [9]));
   na21_b U540 (.Q(n252),
	.A(sd_out[0]),
	.B(n251));
   eo21_b U541 (.Q(n423),
	.A(n252),
	.B(\piece_0/sd_one/sd_reg1 [10]));
   no21_b U542 (.Q(n254),
	.A(n253),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U543 (.Q(n427),
	.A(n254),
	.B(\piece_0/sd_one/sd_reg1 [11]));
   na21_b U544 (.Q(n256),
	.A(sd_out[0]),
	.B(n255));
   eo21_b U545 (.Q(n431),
	.A(n256),
	.B(\piece_0/sd_one/sd_reg1 [12]));
   no21_b U546 (.Q(n258),
	.A(n257),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U547 (.Q(n435),
	.A(n258),
	.B(\piece_0/sd_one/sd_reg1 [13]));
   na21_b U548 (.Q(n260),
	.A(sd_out[0]),
	.B(n259));
   eo21_b U549 (.Q(n439),
	.A(n260),
	.B(\piece_0/sd_one/sd_reg1 [14]));
   no21_b U550 (.Q(n262),
	.A(n261),
	.B(\piece_0/sd_one/sd_reg1 [17]));
   en21_b U551 (.Q(n443),
	.A(n262),
	.B(\piece_0/sd_one/sd_reg1 [15]));
   on11_b U552 (.Q(n264),
	.A(n447),
	.B(n450),
	.C(n449),
	.D(n448));
   on21_b U553 (.Q(n263),
	.A(n451),
	.B(n264),
	.C(n682));
   an21_b U554 (.Q(\piece_0/sd_one/N72 ),
	.A(n451),
	.B(n264),
	.C(n263));
   inv1_b U555 (.Q(n466),
	.A(n268));
   inv1_b U556 (.Q(n624),
	.A(\piece_1/feedback [24]));
   eo21_b U557 (.Q(n460),
	.A(\piece_1/sd_one/sd_reg2 [0]),
	.B(n624));
   na21_b U558 (.Q(n266),
	.A(n464),
	.B(sd_out[1]));
   on21_b U559 (.Q(n265),
	.A(n466),
	.B(n266),
	.C(n682));
   an21_b U560 (.Q(\piece_1/sd_one/N112 ),
	.A(n466),
	.B(n266),
	.C(n265));
   au11_b U561 (.CO(n271),
	.S(n268),
	.A(\piece_1/sd_one/sd_reg2 [1]),
	.B(\piece_1/feedback [25]),
	.CI(n267));
   na21_b U562 (.Q(n273),
	.A(n268),
	.B(n464));
   no21_b U563 (.Q(n270),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n273));
   on21_b U564 (.Q(n269),
	.A(n272),
	.B(n270),
	.C(n682));
   an21_b U565 (.Q(\piece_1/sd_one/N113 ),
	.A(n272),
	.B(n270),
	.C(n269));
   au11_b U566 (.CO(n276),
	.S(n272),
	.A(\piece_1/sd_one/sd_reg2 [2]),
	.B(\piece_1/feedback [26]),
	.CI(n271));
   inv1_b U567 (.Q(n476),
	.A(n278));
   no21_b U568 (.Q(n277),
	.A(n273),
	.B(n472));
   na21_b U569 (.Q(n275),
	.A(n277),
	.B(sd_out[1]));
   on21_b U570 (.Q(n274),
	.A(n476),
	.B(n275),
	.C(n682));
   an21_b U571 (.Q(\piece_1/sd_one/N114 ),
	.A(n476),
	.B(n275),
	.C(n274));
   au11_b U572 (.CO(n281),
	.S(n278),
	.A(\piece_1/sd_one/sd_reg2 [3]),
	.B(\piece_1/feedback [27]),
	.CI(n276));
   na21_b U573 (.Q(n283),
	.A(n278),
	.B(n277));
   no21_b U574 (.Q(n280),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n283));
   on21_b U575 (.Q(n279),
	.A(n282),
	.B(n280),
	.C(n682));
   an21_b U576 (.Q(\piece_1/sd_one/N115 ),
	.A(n282),
	.B(n280),
	.C(n279));
   au11_b U577 (.CO(n286),
	.S(n282),
	.A(\piece_1/sd_one/sd_reg2 [4]),
	.B(\piece_1/feedback [28]),
	.CI(n281));
   inv1_b U578 (.Q(n480),
	.A(n282));
   no21_b U579 (.Q(n287),
	.A(n283),
	.B(n480));
   na21_b U580 (.Q(n285),
	.A(n287),
	.B(sd_out[1]));
   on21_b U581 (.Q(n284),
	.A(n484),
	.B(n285),
	.C(n682));
   an21_b U582 (.Q(\piece_1/sd_one/N116 ),
	.A(n484),
	.B(n285),
	.C(n284));
   au11_b U583 (.CO(n291),
	.S(n288),
	.A(\piece_1/sd_one/sd_reg2 [5]),
	.B(\piece_1/feedback [29]),
	.CI(n286));
   na21_b U584 (.Q(n293),
	.A(n288),
	.B(n287));
   no21_b U585 (.Q(n290),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n293));
   on21_b U586 (.Q(n289),
	.A(n292),
	.B(n290),
	.C(n682));
   an21_b U587 (.Q(\piece_1/sd_one/N117 ),
	.A(n292),
	.B(n290),
	.C(n289));
   au11_b U588 (.CO(n296),
	.S(n292),
	.A(\piece_1/sd_one/sd_reg2 [6]),
	.B(\piece_1/feedback [30]),
	.CI(n291));
   inv1_b U589 (.Q(n492),
	.A(n298));
   inv1_b U590 (.Q(n488),
	.A(n292));
   no21_b U591 (.Q(n297),
	.A(n293),
	.B(n488));
   na21_b U592 (.Q(n295),
	.A(n297),
	.B(sd_out[1]));
   on21_b U593 (.Q(n294),
	.A(n492),
	.B(n295),
	.C(n682));
   an21_b U594 (.Q(\piece_1/sd_one/N118 ),
	.A(n492),
	.B(n295),
	.C(n294));
   au11_b U595 (.CO(n301),
	.S(n298),
	.A(\piece_1/sd_one/sd_reg2 [7]),
	.B(\piece_1/feedback [31]),
	.CI(n296));
   na21_b U596 (.Q(n303),
	.A(n298),
	.B(n297));
   no21_b U597 (.Q(n300),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n303));
   on21_b U598 (.Q(n299),
	.A(n302),
	.B(n300),
	.C(n682));
   an21_b U599 (.Q(\piece_1/sd_one/N119 ),
	.A(n302),
	.B(n300),
	.C(n299));
   au11_b U600 (.CO(n306),
	.S(n302),
	.A(\piece_1/sd_one/sd_reg2 [8]),
	.B(\piece_1/feedback [32]),
	.CI(n301));
   inv1_b U601 (.Q(n496),
	.A(n302));
   no21_b U602 (.Q(n307),
	.A(n303),
	.B(n496));
   na21_b U603 (.Q(n305),
	.A(n307),
	.B(sd_out[1]));
   on21_b U604 (.Q(n304),
	.A(n500),
	.B(n305),
	.C(n682));
   an21_b U605 (.Q(\piece_1/sd_one/N120 ),
	.A(n500),
	.B(n305),
	.C(n304));
   au11_b U606 (.CO(n311),
	.S(n308),
	.A(\piece_1/sd_one/sd_reg2 [9]),
	.B(\piece_1/feedback [33]),
	.CI(n306));
   na21_b U607 (.Q(n313),
	.A(n308),
	.B(n307));
   no21_b U608 (.Q(n310),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n313));
   on21_b U609 (.Q(n309),
	.A(n312),
	.B(n310),
	.C(n682));
   an21_b U610 (.Q(\piece_1/sd_one/N121 ),
	.A(n312),
	.B(n310),
	.C(n309));
   au11_b U611 (.CO(n316),
	.S(n312),
	.A(\piece_1/sd_one/sd_reg2 [10]),
	.B(\piece_1/feedback [34]),
	.CI(n311));
   inv1_b U612 (.Q(n508),
	.A(n318));
   inv1_b U613 (.Q(n504),
	.A(n312));
   no21_b U614 (.Q(n317),
	.A(n313),
	.B(n504));
   na21_b U615 (.Q(n315),
	.A(n317),
	.B(sd_out[1]));
   on21_b U616 (.Q(n314),
	.A(n508),
	.B(n315),
	.C(n682));
   an21_b U617 (.Q(\piece_1/sd_one/N122 ),
	.A(n508),
	.B(n315),
	.C(n314));
   au11_b U618 (.CO(n321),
	.S(n318),
	.A(\piece_1/sd_one/sd_reg2 [11]),
	.B(\piece_1/feedback [35]),
	.CI(n316));
   na21_b U619 (.Q(n323),
	.A(n318),
	.B(n317));
   no21_b U620 (.Q(n320),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n323));
   on21_b U621 (.Q(n319),
	.A(n322),
	.B(n320),
	.C(n682));
   an21_b U622 (.Q(\piece_1/sd_one/N123 ),
	.A(n322),
	.B(n320),
	.C(n319));
   au11_b U623 (.CO(n326),
	.S(n322),
	.A(\piece_1/sd_one/sd_reg2 [12]),
	.B(\piece_1/feedback [36]),
	.CI(n321));
   inv1_b U624 (.Q(n516),
	.A(n328));
   no21_b U625 (.Q(n327),
	.A(n323),
	.B(n512));
   na21_b U626 (.Q(n325),
	.A(n327),
	.B(sd_out[1]));
   on21_b U627 (.Q(n324),
	.A(n516),
	.B(n325),
	.C(n682));
   an21_b U628 (.Q(\piece_1/sd_one/N124 ),
	.A(n516),
	.B(n325),
	.C(n324));
   au11_b U629 (.CO(n334),
	.S(n328),
	.A(\piece_1/sd_one/sd_reg2 [13]),
	.B(\piece_1/feedback [37]),
	.CI(n326));
   inv1_b U630 (.Q(n520),
	.A(n331));
   na21_b U631 (.Q(n329),
	.A(n328),
	.B(n327));
   no21_b U632 (.Q(n330),
	.A(\piece_1/sd_one/sd_reg1 [17]),
	.B(n329));
   inv1_b U633 (.Q(n333),
	.A(n330));
   na21_b U634 (.Q(n462),
	.A(n331),
	.B(n330));
   an31_b U635 (.Q(\piece_1/sd_one/N125 ),
	.A(n520),
	.B(n333),
	.C(reset),
	.D(n332));
   au11_b U636 (.CO(n336),
	.S(n331),
	.A(\piece_1/sd_one/sd_reg2 [14]),
	.B(\piece_1/feedback [38]),
	.CI(n334));
   inv1_b U637 (.Q(n524),
	.A(n335));
   na21_b U638 (.Q(n461),
	.A(n524),
	.B(n462));
   au11_b U639 (.CO(n339),
	.S(n335),
	.A(\piece_1/sd_one/sd_reg2 [15]),
	.B(\piece_1/feedback [39]),
	.CI(n336));
   inv1_b U640 (.Q(n527),
	.A(n529));
   eo21_b U641 (.Q(n337),
	.A(n461),
	.B(n527));
   mx21_b U642 (.Q(\piece_1/sd_one/N127 ),
	.I0(n603),
	.I1(n798),
	.S(n337));
   aa21_b U643 (.Q(n338),
	.A(sd_out[1]),
	.B(n461));
   on11_b U644 (.Q(n341),
	.A(sd_out[1]),
	.B(n461),
	.C(n529),
	.D(n338));
   au11_b U645 (.CO(n340),
	.S(n529),
	.A(\piece_1/sd_one/sd_reg2 [16]),
	.B(\piece_1/feedback [39]),
	.CI(n339));
   eo31_b U646 (.Q(n534),
	.A(\piece_1/feedback [39]),
	.B(\piece_1/sd_one/sd_reg2 [17]),
	.C(n340));
   eo21_b U647 (.Q(n342),
	.A(n341),
	.B(n534));
   mx21_b U648 (.Q(\piece_1/sd_one/N128 ),
	.I0(n603),
	.I1(n798),
	.S(n342));
   na21_b U649 (.Q(n351),
	.A(\piece_1/sd_one/sd_reg1 [16]),
	.B(sd_out[1]));
   on21_b U650 (.Q(n350),
	.A(\piece_1/sd_one/sd_reg1 [16]),
	.B(sd_out[1]),
	.C(n351));
   na21_b U651 (.Q(n353),
	.A(\piece_1/sd_one/sd_reg1 [2]),
	.B(\piece_1/sd_one/sd_reg1 [1]));
   inv1_b U652 (.Q(n343),
	.A(\piece_1/sd_one/sd_reg1 [3]));
   no21_b U653 (.Q(n355),
	.A(n353),
	.B(n343));
   na21_b U654 (.Q(n357),
	.A(\piece_1/sd_one/sd_reg1 [4]),
	.B(n355));
   inv1_b U655 (.Q(n344),
	.A(\piece_1/sd_one/sd_reg1 [5]));
   no21_b U656 (.Q(n359),
	.A(n357),
	.B(n344));
   na21_b U657 (.Q(n361),
	.A(\piece_1/sd_one/sd_reg1 [6]),
	.B(n359));
   inv1_b U658 (.Q(n345),
	.A(\piece_1/sd_one/sd_reg1 [7]));
   no21_b U659 (.Q(n363),
	.A(n361),
	.B(n345));
   na21_b U660 (.Q(n365),
	.A(\piece_1/sd_one/sd_reg1 [8]),
	.B(n363));
   inv1_b U661 (.Q(n346),
	.A(\piece_1/sd_one/sd_reg1 [9]));
   no21_b U662 (.Q(n367),
	.A(n365),
	.B(n346));
   na21_b U663 (.Q(n369),
	.A(\piece_1/sd_one/sd_reg1 [10]),
	.B(n367));
   inv1_b U664 (.Q(n347),
	.A(\piece_1/sd_one/sd_reg1 [11]));
   no21_b U665 (.Q(n371),
	.A(n369),
	.B(n347));
   na21_b U666 (.Q(n373),
	.A(\piece_1/sd_one/sd_reg1 [12]),
	.B(n371));
   inv1_b U667 (.Q(n348),
	.A(\piece_1/sd_one/sd_reg1 [13]));
   no21_b U668 (.Q(n375),
	.A(n373),
	.B(n348));
   na21_b U669 (.Q(n377),
	.A(\piece_1/sd_one/sd_reg1 [14]),
	.B(n375));
   inv1_b U670 (.Q(n349),
	.A(\piece_1/sd_one/sd_reg1 [15]));
   on21_b U671 (.Q(n533),
	.A(n377),
	.B(n349),
	.C(sd_out[1]));
   mx21_b U672 (.Q(n530),
	.I0(n351),
	.I1(n350),
	.S(n533));
   en21_b U673 (.Q(n468),
	.A(\piece_1/sd_one/sd_reg1 [1]),
	.B(sd_out[1]));
   na21_b U674 (.Q(n467),
	.A(n464),
	.B(\piece_1/sd_one/sd_reg1 [0]));
   na21_b U675 (.Q(n352),
	.A(sd_out[1]),
	.B(\piece_1/sd_one/sd_reg1 [1]));
   eo21_b U676 (.Q(n470),
	.A(n352),
	.B(\piece_1/sd_one/sd_reg1 [2]));
   no21_b U677 (.Q(n354),
	.A(n353),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U678 (.Q(n474),
	.A(n354),
	.B(\piece_1/sd_one/sd_reg1 [3]));
   na21_b U679 (.Q(n356),
	.A(sd_out[1]),
	.B(n355));
   eo21_b U680 (.Q(n478),
	.A(n356),
	.B(\piece_1/sd_one/sd_reg1 [4]));
   no21_b U681 (.Q(n358),
	.A(n357),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U682 (.Q(n482),
	.A(n358),
	.B(\piece_1/sd_one/sd_reg1 [5]));
   na21_b U683 (.Q(n360),
	.A(sd_out[1]),
	.B(n359));
   eo21_b U684 (.Q(n486),
	.A(n360),
	.B(\piece_1/sd_one/sd_reg1 [6]));
   no21_b U685 (.Q(n362),
	.A(n361),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U686 (.Q(n490),
	.A(n362),
	.B(\piece_1/sd_one/sd_reg1 [7]));
   na21_b U687 (.Q(n364),
	.A(sd_out[1]),
	.B(n363));
   eo21_b U688 (.Q(n494),
	.A(n364),
	.B(\piece_1/sd_one/sd_reg1 [8]));
   no21_b U689 (.Q(n366),
	.A(n365),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U690 (.Q(n498),
	.A(n366),
	.B(\piece_1/sd_one/sd_reg1 [9]));
   na21_b U691 (.Q(n368),
	.A(sd_out[1]),
	.B(n367));
   eo21_b U692 (.Q(n502),
	.A(n368),
	.B(\piece_1/sd_one/sd_reg1 [10]));
   no21_b U693 (.Q(n370),
	.A(n369),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U694 (.Q(n506),
	.A(n370),
	.B(\piece_1/sd_one/sd_reg1 [11]));
   na21_b U695 (.Q(n372),
	.A(sd_out[1]),
	.B(n371));
   eo21_b U696 (.Q(n510),
	.A(n372),
	.B(\piece_1/sd_one/sd_reg1 [12]));
   no21_b U697 (.Q(n374),
	.A(n373),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U698 (.Q(n514),
	.A(n374),
	.B(\piece_1/sd_one/sd_reg1 [13]));
   na21_b U699 (.Q(n376),
	.A(sd_out[1]),
	.B(n375));
   eo21_b U700 (.Q(n518),
	.A(n376),
	.B(\piece_1/sd_one/sd_reg1 [14]));
   no21_b U701 (.Q(n378),
	.A(n377),
	.B(\piece_1/sd_one/sd_reg1 [17]));
   en21_b U702 (.Q(n522),
	.A(n378),
	.B(\piece_1/sd_one/sd_reg1 [15]));
   on11_b U703 (.Q(n380),
	.A(n526),
	.B(n529),
	.C(n528),
	.D(n527));
   on21_b U704 (.Q(n379),
	.A(n530),
	.B(n380),
	.C(n682));
   an21_b U705 (.Q(\piece_1/sd_one/N72 ),
	.A(n530),
	.B(n380),
	.C(n379));
   inv1_b U706 (.Q(n381),
	.A(n385));
   on11_b U707 (.Q(\piece_0/sd_one/N111 ),
	.A(n385),
	.B(n634),
	.C(n381),
	.D(n616));
   on21_b U708 (.Q(n384),
	.A(n383),
	.B(n445),
	.C(n382));
   aa21_b U709 (.Q(\piece_0/sd_one/N126 ),
	.A(n682),
	.B(n384));
   on21_b U710 (.Q(n386),
	.A(n385),
	.B(\piece_0/sd_one/sd_reg1 [0]),
	.C(n388));
   no21_b U711 (.Q(\piece_0/sd_one/N56 ),
	.A(reset),
	.B(n386));
   au11_b U712 (.CO(n392),
	.S(n390),
	.A(n389),
	.B(n388),
	.CI(n387));
   no21_b U713 (.Q(\piece_0/sd_one/N57 ),
	.A(reset),
	.B(n390));
   au11_b U714 (.CO(n396),
	.S(n394),
	.A(n393),
	.B(n392),
	.CI(n391));
   no21_b U715 (.Q(\piece_0/sd_one/N58 ),
	.A(reset),
	.B(n394));
   au11_b U716 (.CO(n400),
	.S(n398),
	.A(n397),
	.B(n396),
	.CI(n395));
   no21_b U717 (.Q(\piece_0/sd_one/N59 ),
	.A(reset),
	.B(n398));
   au11_b U718 (.CO(n404),
	.S(n402),
	.A(n401),
	.B(n400),
	.CI(n399));
   no21_b U719 (.Q(\piece_0/sd_one/N60 ),
	.A(reset),
	.B(n402));
   au11_b U720 (.CO(n408),
	.S(n406),
	.A(n405),
	.B(n404),
	.CI(n403));
   no21_b U721 (.Q(\piece_0/sd_one/N61 ),
	.A(reset),
	.B(n406));
   au11_b U722 (.CO(n412),
	.S(n410),
	.A(n409),
	.B(n408),
	.CI(n407));
   no21_b U723 (.Q(\piece_0/sd_one/N62 ),
	.A(reset),
	.B(n410));
   au11_b U724 (.CO(n416),
	.S(n414),
	.A(n413),
	.B(n412),
	.CI(n411));
   no21_b U725 (.Q(\piece_0/sd_one/N63 ),
	.A(reset),
	.B(n414));
   au11_b U726 (.CO(n420),
	.S(n418),
	.A(n417),
	.B(n416),
	.CI(n415));
   no21_b U727 (.Q(\piece_0/sd_one/N64 ),
	.A(reset),
	.B(n418));
   au11_b U728 (.CO(n424),
	.S(n422),
	.A(n421),
	.B(n420),
	.CI(n419));
   no21_b U729 (.Q(\piece_0/sd_one/N65 ),
	.A(reset),
	.B(n422));
   au11_b U730 (.CO(n428),
	.S(n426),
	.A(n425),
	.B(n424),
	.CI(n423));
   no21_b U731 (.Q(\piece_0/sd_one/N66 ),
	.A(reset),
	.B(n426));
   au11_b U732 (.CO(n432),
	.S(n430),
	.A(n429),
	.B(n428),
	.CI(n427));
   no21_b U733 (.Q(\piece_0/sd_one/N67 ),
	.A(reset),
	.B(n430));
   au11_b U734 (.CO(n436),
	.S(n434),
	.A(n433),
	.B(n432),
	.CI(n431));
   no21_b U735 (.Q(\piece_0/sd_one/N68 ),
	.A(reset),
	.B(n434));
   au11_b U736 (.CO(n440),
	.S(n438),
	.A(n437),
	.B(n436),
	.CI(n435));
   no21_b U737 (.Q(\piece_0/sd_one/N69 ),
	.A(reset),
	.B(n438));
   au11_b U738 (.CO(n444),
	.S(n442),
	.A(n441),
	.B(n440),
	.CI(n439));
   no21_b U739 (.Q(\piece_0/sd_one/N70 ),
	.A(reset),
	.B(n442));
   au11_b U740 (.CO(n447),
	.S(n446),
	.A(n445),
	.B(n444),
	.CI(n443));
   no21_b U741 (.Q(\piece_0/sd_one/N71 ),
	.A(reset),
	.B(n446));
   no21_b U742 (.Q(n452),
	.A(n448),
	.B(n447));
   on11_b U743 (.Q(n458),
	.A(n452),
	.B(n451),
	.C(n450),
	.D(n449));
   an21_b U744 (.Q(n456),
	.A(n454),
	.B(sd_out[0]),
	.C(\piece_0/sd_one/sd_reg1 [16]));
   en21_b U745 (.Q(n457),
	.A(n456),
	.B(n455));
   en21_b U746 (.Q(n459),
	.A(n458),
	.B(n457));
   no21_b U747 (.Q(\piece_0/sd_one/N73 ),
	.A(reset),
	.B(n459));
   on11_b U748 (.Q(\piece_1/sd_one/N111 ),
	.A(n464),
	.B(n806),
	.C(n460),
	.D(n747));
   on21_b U749 (.Q(n463),
	.A(n462),
	.B(n524),
	.C(n461));
   aa21_b U750 (.Q(\piece_1/sd_one/N126 ),
	.A(n682),
	.B(n463));
   on21_b U751 (.Q(n465),
	.A(n464),
	.B(\piece_1/sd_one/sd_reg1 [0]),
	.C(n467));
   no21_b U752 (.Q(\piece_1/sd_one/N56 ),
	.A(reset),
	.B(n465));
   au11_b U753 (.CO(n471),
	.S(n469),
	.A(n468),
	.B(n467),
	.CI(n466));
   no21_b U754 (.Q(\piece_1/sd_one/N57 ),
	.A(reset),
	.B(n469));
   au11_b U755 (.CO(n475),
	.S(n473),
	.A(n472),
	.B(n471),
	.CI(n470));
   no21_b U756 (.Q(\piece_1/sd_one/N58 ),
	.A(reset),
	.B(n473));
   au11_b U757 (.CO(n479),
	.S(n477),
	.A(n476),
	.B(n475),
	.CI(n474));
   no21_b U758 (.Q(\piece_1/sd_one/N59 ),
	.A(reset),
	.B(n477));
   au11_b U759 (.CO(n483),
	.S(n481),
	.A(n480),
	.B(n479),
	.CI(n478));
   no21_b U760 (.Q(\piece_1/sd_one/N60 ),
	.A(reset),
	.B(n481));
   au11_b U761 (.CO(n487),
	.S(n485),
	.A(n484),
	.B(n483),
	.CI(n482));
   no21_b U762 (.Q(\piece_1/sd_one/N61 ),
	.A(reset),
	.B(n485));
   au11_b U763 (.CO(n491),
	.S(n489),
	.A(n488),
	.B(n487),
	.CI(n486));
   no21_b U764 (.Q(\piece_1/sd_one/N62 ),
	.A(reset),
	.B(n489));
   au11_b U765 (.CO(n495),
	.S(n493),
	.A(n492),
	.B(n491),
	.CI(n490));
   no21_b U766 (.Q(\piece_1/sd_one/N63 ),
	.A(reset),
	.B(n493));
   au11_b U767 (.CO(n499),
	.S(n497),
	.A(n496),
	.B(n495),
	.CI(n494));
   no21_b U768 (.Q(\piece_1/sd_one/N64 ),
	.A(reset),
	.B(n497));
   au11_b U769 (.CO(n503),
	.S(n501),
	.A(n500),
	.B(n499),
	.CI(n498));
   no21_b U770 (.Q(\piece_1/sd_one/N65 ),
	.A(reset),
	.B(n501));
   au11_b U771 (.CO(n507),
	.S(n505),
	.A(n504),
	.B(n503),
	.CI(n502));
   no21_b U772 (.Q(\piece_1/sd_one/N66 ),
	.A(reset),
	.B(n505));
   au11_b U773 (.CO(n511),
	.S(n509),
	.A(n508),
	.B(n507),
	.CI(n506));
   no21_b U774 (.Q(\piece_1/sd_one/N67 ),
	.A(reset),
	.B(n509));
   au11_b U775 (.CO(n515),
	.S(n513),
	.A(n512),
	.B(n511),
	.CI(n510));
   no21_b U776 (.Q(\piece_1/sd_one/N68 ),
	.A(reset),
	.B(n513));
   au11_b U777 (.CO(n519),
	.S(n517),
	.A(n516),
	.B(n515),
	.CI(n514));
   no21_b U778 (.Q(\piece_1/sd_one/N69 ),
	.A(reset),
	.B(n517));
   au11_b U779 (.CO(n523),
	.S(n521),
	.A(n520),
	.B(n519),
	.CI(n518));
   no21_b U780 (.Q(\piece_1/sd_one/N70 ),
	.A(reset),
	.B(n521));
   au11_b U781 (.CO(n526),
	.S(n525),
	.A(n524),
	.B(n523),
	.CI(n522));
   no21_b U782 (.Q(\piece_1/sd_one/N71 ),
	.A(reset),
	.B(n525));
   no21_b U783 (.Q(n531),
	.A(n527),
	.B(n526));
   on11_b U784 (.Q(n537),
	.A(n531),
	.B(n530),
	.C(n529),
	.D(n528));
   an21_b U785 (.Q(n535),
	.A(n533),
	.B(sd_out[1]),
	.C(\piece_1/sd_one/sd_reg1 [16]));
   en21_b U786 (.Q(n536),
	.A(n535),
	.B(n534));
   en21_b U787 (.Q(n538),
	.A(n537),
	.B(n536));
   no21_b U788 (.Q(\piece_1/sd_one/N73 ),
	.A(reset),
	.B(n538));
   no21_b U789 (.Q(n550),
	.A(\piece_1/feedback [17]),
	.B(sd_out[1]));
   inv1_b U790 (.Q(n597),
	.A(\piece_1/feedback [16]));
   on21_b U791 (.Q(n539),
	.A(n636),
	.B(\piece_1/feedback [6]),
	.C(\piece_1/feedback [7]));
   inv1_b U792 (.Q(n577),
	.A(\piece_1/feedback [6]));
   on21_b U793 (.Q(n580),
	.A(n577),
	.B(n634),
	.C(n539));
   on21_b U794 (.Q(n540),
	.A(n713),
	.B(n580),
	.C(\piece_1/feedback [8]));
   on21_b U795 (.Q(n582),
	.A(n539),
	.B(n616),
	.C(n540));
   on21_b U796 (.Q(n541),
	.A(n636),
	.B(n582),
	.C(\piece_1/feedback [9]));
   on21_b U797 (.Q(n584),
	.A(n540),
	.B(n634),
	.C(n541));
   on21_b U798 (.Q(n543),
	.A(n713),
	.B(n584),
	.C(\piece_1/feedback [10]));
   on21_b U799 (.Q(n586),
	.A(n541),
	.B(n616),
	.C(n543));
   inv1_b U800 (.Q(n542),
	.A(\piece_1/feedback [11]));
   an21_b U801 (.Q(n544),
	.A(n616),
	.B(n543),
	.C(n542));
   an21_b U802 (.Q(n588),
	.A(n713),
	.B(n586),
	.C(n544));
   on21_b U803 (.Q(n547),
	.A(n713),
	.B(n544),
	.C(\piece_1/feedback [12]));
   on21_b U804 (.Q(n590),
	.A(n588),
	.B(n616),
	.C(n547));
   on21_b U805 (.Q(n546),
	.A(n636),
	.B(n590),
	.C(\piece_1/feedback [13]));
   inv1_b U806 (.Q(n545),
	.A(\piece_1/feedback [14]));
   an21_b U807 (.Q(n549),
	.A(n634),
	.B(n546),
	.C(n545));
   on21_b U808 (.Q(n592),
	.A(n547),
	.B(n634),
	.C(n546));
   an21_b U809 (.Q(n594),
	.A(n636),
	.B(n592),
	.C(n549));
   no21_b U810 (.Q(n548),
	.A(n594),
	.B(n634));
   on11_b U811 (.Q(n596),
	.A(n636),
	.B(n549),
	.C(n548),
	.D(\piece_1/feedback [15]));
   na21_b U812 (.Q(n599),
	.A(\piece_1/feedback [17]),
	.B(sd_out[1]));
   on21_b U813 (.Q(n605),
	.A(n550),
	.B(n600),
	.C(n599));
   inv1_b U814 (.Q(n603),
	.A(n747));
   aa21_b U815 (.Q(n551),
	.A(n605),
	.B(n603));
   on11_b U816 (.Q(n608),
	.A(n605),
	.B(n603),
	.C(\piece_1/feedback [18]),
	.D(n551));
   na21_b U817 (.Q(n607),
	.A(n636),
	.B(\piece_1/feedback [19]));
   no21_b U818 (.Q(n552),
	.A(n636),
	.B(\piece_1/feedback [19]));
   an21_b U819 (.Q(n611),
	.A(n608),
	.B(n607),
	.C(n552));
   on21_b U820 (.Q(n556),
	.A(n636),
	.B(n614),
	.C(\piece_1/feedback [21]));
   na31_b U821 (.Q(n553),
	.A(n611),
	.B(\piece_1/feedback [20]),
	.C(n636));
   na21_b U822 (.Q(n618),
	.A(n556),
	.B(n553));
   on21_b U823 (.Q(n555),
	.A(n713),
	.B(n618),
	.C(\piece_1/feedback [22]));
   on21_b U824 (.Q(n558),
	.A(n713),
	.B(n554),
	.C(\piece_1/feedback [23]));
   an21_b U825 (.Q(n559),
	.A(n616),
	.B(n558),
	.C(n624));
   on21_b U826 (.Q(n557),
	.A(n556),
	.B(n616),
	.C(n555));
   on21_b U827 (.Q(n625),
	.A(n621),
	.B(n616),
	.C(n558));
   an21_b U828 (.Q(n630),
	.A(n713),
	.B(n625),
	.C(n559));
   inv1_b U829 (.Q(n628),
	.A(\piece_1/feedback [25]));
   an21_b U830 (.Q(n560),
	.A(n630),
	.B(n634),
	.C(n628));
   an21_b U831 (.Q(n632),
	.A(n559),
	.B(n636),
	.C(n560));
   on21_b U832 (.Q(n561),
	.A(n636),
	.B(n560),
	.C(\piece_1/feedback [26]));
   on21_b U833 (.Q(n637),
	.A(n632),
	.B(n634),
	.C(n561));
   inv1_b U834 (.Q(n635),
	.A(\piece_1/feedback [27]));
   an21_b U835 (.Q(n564),
	.A(n634),
	.B(n561),
	.C(n635));
   an21_b U836 (.Q(n641),
	.A(n636),
	.B(n637),
	.C(n564));
   inv1_b U837 (.Q(n562),
	.A(\piece_1/feedback [28]));
   an21_b U838 (.Q(n563),
	.A(n641),
	.B(n616),
	.C(n562));
   on21_b U839 (.Q(n565),
	.A(n713),
	.B(n563),
	.C(\piece_1/feedback [29]));
   inv1_b U840 (.Q(n647),
	.A(\piece_1/feedback [30]));
   an21_b U841 (.Q(n566),
	.A(n616),
	.B(n565),
	.C(n647));
   on21_b U842 (.Q(n567),
	.A(n713),
	.B(n566),
	.C(\piece_1/feedback [31]));
   inv1_b U843 (.Q(n654),
	.A(\piece_1/feedback [32]));
   an21_b U844 (.Q(n568),
	.A(n616),
	.B(n567),
	.C(n654));
   on21_b U845 (.Q(n569),
	.A(n713),
	.B(n568),
	.C(\piece_1/feedback [33]));
   inv1_b U846 (.Q(n661),
	.A(\piece_1/feedback [34]));
   an21_b U847 (.Q(n570),
	.A(n616),
	.B(n569),
	.C(n661));
   on21_b U848 (.Q(n571),
	.A(n713),
	.B(n570),
	.C(\piece_1/feedback [35]));
   inv1_b U849 (.Q(n668),
	.A(\piece_1/feedback [36]));
   an21_b U850 (.Q(n572),
	.A(n616),
	.B(n571),
	.C(n668));
   on21_b U851 (.Q(n573),
	.A(n713),
	.B(n572),
	.C(\piece_1/feedback [37]));
   inv1_b U852 (.Q(n675),
	.A(\piece_1/feedback [38]));
   no21_b U853 (.Q(n574),
	.A(n573),
	.B(n675));
   an21_b U854 (.Q(n644),
	.A(n564),
	.B(n713),
	.C(n563));
   on21_b U855 (.Q(n648),
	.A(n644),
	.B(n616),
	.C(n565));
   an21_b U856 (.Q(n651),
	.A(n713),
	.B(n648),
	.C(n566));
   on21_b U857 (.Q(n655),
	.A(n651),
	.B(n616),
	.C(n567));
   an21_b U858 (.Q(n658),
	.A(n713),
	.B(n655),
	.C(n568));
   on21_b U859 (.Q(n662),
	.A(n658),
	.B(n616),
	.C(n569));
   an21_b U860 (.Q(n665),
	.A(n713),
	.B(n662),
	.C(n570));
   on21_b U861 (.Q(n669),
	.A(n665),
	.B(n616),
	.C(n571));
   an21_b U862 (.Q(n672),
	.A(n713),
	.B(n669),
	.C(n572));
   on21_b U863 (.Q(n676),
	.A(n672),
	.B(n616),
	.C(n573));
   on11_b U864 (.Q(n683),
	.A(n574),
	.B(n713),
	.C(\piece_1/feedback [38]),
	.D(n676));
   na31_b U865 (.Q(n575),
	.A(\piece_1/feedback [39]),
	.B(n713),
	.C(n683));
   on41_b U866 (.Q(n576),
	.A(\piece_1/feedback [39]),
	.B(n713),
	.C(n683),
	.D(n575));
   no21_b U867 (.Q(n617),
	.A(reset),
	.B(n576));
   na21_b U868 (.Q(n680),
	.A(n636),
	.B(n576));
   on21_b U869 (.Q(\piece_1/N16 ),
	.A(\piece_1/feedback [6]),
	.B(n639),
	.C(n680));
   on11_b U870 (.Q(n578),
	.A(n636),
	.B(\piece_1/feedback [6]),
	.C(n634),
	.D(n577));
   eo21_b U871 (.Q(n579),
	.A(n578),
	.B(\piece_1/feedback [7]));
   on21_b U872 (.Q(\piece_1/N17 ),
	.A(n579),
	.B(n639),
	.C(n680));
   eo31_b U873 (.Q(n581),
	.A(\piece_1/feedback [8]),
	.B(n616),
	.C(n580));
   on21_b U874 (.Q(\piece_1/N18 ),
	.A(n581),
	.B(n639),
	.C(n680));
   eo31_b U875 (.Q(n583),
	.A(\piece_1/feedback [9]),
	.B(n634),
	.C(n582));
   on21_b U876 (.Q(\piece_1/N19 ),
	.A(n583),
	.B(n639),
	.C(n680));
   eo31_b U877 (.Q(n585),
	.A(\piece_1/feedback [10]),
	.B(n616),
	.C(n584));
   on21_b U878 (.Q(\piece_1/N20 ),
	.A(n585),
	.B(n639),
	.C(n680));
   eo31_b U879 (.Q(n587),
	.A(\piece_1/feedback [11]),
	.B(n616),
	.C(n586));
   on21_b U880 (.Q(\piece_1/N21 ),
	.A(n587),
	.B(n639),
	.C(n680));
   eo31_b U881 (.Q(n589),
	.A(n713),
	.B(\piece_1/feedback [12]),
	.C(n588));
   on21_b U882 (.Q(\piece_1/N22 ),
	.A(n589),
	.B(n639),
	.C(n680));
   eo31_b U883 (.Q(n591),
	.A(\piece_1/feedback [13]),
	.B(n634),
	.C(n590));
   on21_b U884 (.Q(\piece_1/N23 ),
	.A(n591),
	.B(n639),
	.C(n680));
   eo31_b U885 (.Q(n593),
	.A(\piece_1/feedback [14]),
	.B(n634),
	.C(n592));
   on21_b U886 (.Q(\piece_1/N24 ),
	.A(n593),
	.B(n639),
	.C(n680));
   eo31_b U887 (.Q(n595),
	.A(n636),
	.B(n594),
	.C(\piece_1/feedback [15]));
   on21_b U888 (.Q(\piece_1/N25 ),
	.A(n595),
	.B(n639),
	.C(n680));
   au11_b U889 (.CO(n600),
	.S(n598),
	.A(n597),
	.B(n713),
	.CI(n596));
   on21_b U890 (.Q(\piece_1/N26 ),
	.A(n598),
	.B(n639),
	.C(n680));
   on21_b U891 (.Q(n601),
	.A(\piece_1/feedback [17]),
	.B(sd_out[1]),
	.C(n599));
   en21_b U892 (.Q(n602),
	.A(n601),
	.B(n600));
   on21_b U893 (.Q(\piece_1/N27 ),
	.A(n639),
	.B(n602),
	.C(n680));
   eo21_b U894 (.Q(n604),
	.A(\piece_1/feedback [18]),
	.B(n603));
   en21_b U895 (.Q(n606),
	.A(n605),
	.B(n604));
   on21_b U896 (.Q(\piece_1/N28 ),
	.A(n639),
	.B(n606),
	.C(n680));
   on21_b U897 (.Q(n609),
	.A(n636),
	.B(\piece_1/feedback [19]),
	.C(n607));
   en21_b U898 (.Q(n610),
	.A(n609),
	.B(n608));
   on21_b U899 (.Q(\piece_1/N29 ),
	.A(n639),
	.B(n610),
	.C(n680));
   au11_b U900 (.CO(n614),
	.S(n612),
	.A(\piece_1/feedback [20]),
	.B(n713),
	.CI(n611));
   na21_b U901 (.Q(n613),
	.A(n617),
	.B(n612));
   na21_b U902 (.Q(\piece_1/N30 ),
	.A(n680),
	.B(n613));
   eo31_b U903 (.Q(n615),
	.A(n614),
	.B(\piece_1/feedback [21]),
	.C(n634));
   on21_b U904 (.Q(\piece_1/N31 ),
	.A(n639),
	.B(n615),
	.C(n680));
   na21_b U905 (.Q(n679),
	.A(n617),
	.B(n616));
   na21_b U906 (.Q(n678),
	.A(n713),
	.B(n617));
   en21_b U907 (.Q(n619),
	.A(\piece_1/feedback [22]),
	.B(n618));
   mx21_b U908 (.Q(n620),
	.I0(n679),
	.I1(n678),
	.S(n619));
   na21_b U909 (.Q(\piece_1/N32 ),
	.A(n620),
	.B(n680));
   eo21_b U910 (.Q(n622),
	.A(n621),
	.B(\piece_1/feedback [23]));
   mx21_b U911 (.Q(n623),
	.I0(n679),
	.I1(n678),
	.S(n622));
   na21_b U912 (.Q(\piece_1/N33 ),
	.A(n623),
	.B(n680));
   eo21_b U913 (.Q(n626),
	.A(n625),
	.B(n624));
   mx21_b U914 (.Q(n627),
	.I0(n679),
	.I1(n678),
	.S(n626));
   na21_b U915 (.Q(\piece_1/N34 ),
	.A(n627),
	.B(n680));
   on11_b U916 (.Q(n629),
	.A(n636),
	.B(\piece_1/feedback [25]),
	.C(n634),
	.D(n628));
   en21_b U917 (.Q(n631),
	.A(n630),
	.B(n629));
   on21_b U918 (.Q(\piece_1/N35 ),
	.A(n631),
	.B(n639),
	.C(n680));
   eo31_b U919 (.Q(n633),
	.A(n636),
	.B(\piece_1/feedback [26]),
	.C(n632));
   on21_b U920 (.Q(\piece_1/N36 ),
	.A(n633),
	.B(n639),
	.C(n680));
   on11_b U921 (.Q(n638),
	.A(n636),
	.B(n635),
	.C(n634),
	.D(\piece_1/feedback [27]));
   en21_b U922 (.Q(n640),
	.A(n638),
	.B(n637));
   on21_b U923 (.Q(\piece_1/N37 ),
	.A(n640),
	.B(n639),
	.C(n680));
   eo21_b U924 (.Q(n642),
	.A(\piece_1/feedback [28]),
	.B(n641));
   mx21_b U925 (.Q(n643),
	.I0(n679),
	.I1(n678),
	.S(n642));
   na21_b U926 (.Q(\piece_1/N38 ),
	.A(n643),
	.B(n680));
   eo21_b U927 (.Q(n645),
	.A(n644),
	.B(\piece_1/feedback [29]));
   mx21_b U928 (.Q(n646),
	.I0(n679),
	.I1(n678),
	.S(n645));
   na21_b U929 (.Q(\piece_1/N39 ),
	.A(n646),
	.B(n680));
   eo21_b U930 (.Q(n649),
	.A(n648),
	.B(n647));
   mx21_b U931 (.Q(n650),
	.I0(n679),
	.I1(n678),
	.S(n649));
   na21_b U932 (.Q(\piece_1/N40 ),
	.A(n650),
	.B(n680));
   eo21_b U933 (.Q(n652),
	.A(n651),
	.B(\piece_1/feedback [31]));
   mx21_b U934 (.Q(n653),
	.I0(n679),
	.I1(n678),
	.S(n652));
   na21_b U935 (.Q(\piece_1/N41 ),
	.A(n653),
	.B(n680));
   eo21_b U936 (.Q(n656),
	.A(n655),
	.B(n654));
   mx21_b U937 (.Q(n657),
	.I0(n679),
	.I1(n678),
	.S(n656));
   na21_b U938 (.Q(\piece_1/N42 ),
	.A(n657),
	.B(n680));
   eo21_b U939 (.Q(n659),
	.A(n658),
	.B(\piece_1/feedback [33]));
   mx21_b U940 (.Q(n660),
	.I0(n679),
	.I1(n678),
	.S(n659));
   na21_b U941 (.Q(\piece_1/N43 ),
	.A(n660),
	.B(n680));
   eo21_b U942 (.Q(n663),
	.A(n662),
	.B(n661));
   mx21_b U943 (.Q(n664),
	.I0(n679),
	.I1(n678),
	.S(n663));
   na21_b U944 (.Q(\piece_1/N44 ),
	.A(n664),
	.B(n680));
   eo21_b U945 (.Q(n666),
	.A(n665),
	.B(\piece_1/feedback [35]));
   mx21_b U946 (.Q(n667),
	.I0(n679),
	.I1(n678),
	.S(n666));
   na21_b U947 (.Q(\piece_1/N45 ),
	.A(n667),
	.B(n680));
   eo21_b U948 (.Q(n670),
	.A(n669),
	.B(n668));
   mx21_b U949 (.Q(n671),
	.I0(n679),
	.I1(n678),
	.S(n670));
   na21_b U950 (.Q(\piece_1/N46 ),
	.A(n671),
	.B(n680));
   eo21_b U951 (.Q(n673),
	.A(n672),
	.B(\piece_1/feedback [37]));
   mx21_b U952 (.Q(n674),
	.I0(n679),
	.I1(n678),
	.S(n673));
   na21_b U953 (.Q(\piece_1/N47 ),
	.A(n674),
	.B(n680));
   eo21_b U954 (.Q(n677),
	.A(n676),
	.B(n675));
   mx21_b U955 (.Q(n681),
	.I0(n679),
	.I1(n678),
	.S(n677));
   na21_b U956 (.Q(\piece_1/N48 ),
	.A(n681),
	.B(n680));
   on31_b U957 (.Q(n685),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n683),
	.C(n682),
	.D(\piece_1/feedback [39]));
   na31_b U958 (.Q(n684),
	.A(\piece_0/sd_one/sd_reg1 [17]),
	.B(n683),
	.C(n682));
   na21_b U959 (.Q(\piece_1/N49 ),
	.A(n685),
	.B(n684));
   on21_b U960 (.Q(\piece_0/N16 ),
	.A(n102),
	.B(\piece_0/feedback [6]),
	.C(n817));
   on11_b U961 (.Q(n688),
	.A(n603),
	.B(n687),
	.C(n747),
	.D(\piece_0/feedback [6]));
   en21_b U962 (.Q(n689),
	.A(\piece_0/feedback [7]),
	.B(n688));
   on21_b U963 (.Q(\piece_0/N17 ),
	.A(n102),
	.B(n689),
	.C(n817));
   eo31_b U964 (.Q(n691),
	.A(\piece_0/feedback [8]),
	.B(n806),
	.C(n690));
   on21_b U965 (.Q(\piece_0/N18 ),
	.A(n102),
	.B(n691),
	.C(n817));
   eo31_b U966 (.Q(n693),
	.A(\piece_0/feedback [9]),
	.B(n747),
	.C(n692));
   on21_b U967 (.Q(\piece_0/N19 ),
	.A(n102),
	.B(n693),
	.C(n817));
   eo31_b U968 (.Q(n695),
	.A(\piece_0/feedback [10]),
	.B(n806),
	.C(n694));
   on21_b U969 (.Q(\piece_0/N20 ),
	.A(n102),
	.B(n695),
	.C(n817));
   eo31_b U970 (.Q(n697),
	.A(\piece_0/feedback [11]),
	.B(n806),
	.C(n696));
   on21_b U971 (.Q(\piece_0/N21 ),
	.A(n102),
	.B(n697),
	.C(n817));
   eo31_b U972 (.Q(n699),
	.A(n798),
	.B(\piece_0/feedback [12]),
	.C(n698));
   on21_b U973 (.Q(\piece_0/N22 ),
	.A(n102),
	.B(n699),
	.C(n817));
   eo31_b U974 (.Q(n701),
	.A(\piece_0/feedback [13]),
	.B(n747),
	.C(n700));
   on21_b U975 (.Q(\piece_0/N23 ),
	.A(n102),
	.B(n701),
	.C(n817));
   eo31_b U976 (.Q(n703),
	.A(\piece_0/feedback [14]),
	.B(n747),
	.C(n702));
   on21_b U977 (.Q(\piece_0/N24 ),
	.A(n102),
	.B(n703),
	.C(n817));
   eo31_b U978 (.Q(n705),
	.A(n603),
	.B(n704),
	.C(\piece_0/feedback [15]));
   on21_b U979 (.Q(\piece_0/N25 ),
	.A(n102),
	.B(n705),
	.C(n817));
   au11_b U980 (.CO(n711),
	.S(n708),
	.A(n707),
	.B(n798),
	.CI(n706));
   on21_b U981 (.Q(\piece_0/N26 ),
	.A(n102),
	.B(n708),
	.C(n817));
   on21_b U982 (.Q(n710),
	.A(\piece_0/feedback [17]),
	.B(sd_out[0]),
	.C(n709));
   en21_b U983 (.Q(n712),
	.A(n711),
	.B(n710));
   on21_b U984 (.Q(\piece_0/N27 ),
	.A(n102),
	.B(n712),
	.C(n817));
   eo21_b U985 (.Q(n714),
	.A(\piece_0/feedback [18]),
	.B(n713));
   en21_b U986 (.Q(n716),
	.A(n715),
	.B(n714));
   on21_b U987 (.Q(\piece_0/N28 ),
	.A(n102),
	.B(n716),
	.C(n817));
   no21_b U988 (.Q(n718),
	.A(n603),
	.B(\piece_0/feedback [19]));
   no21_b U989 (.Q(n719),
	.A(n718),
	.B(n717));
   en21_b U990 (.Q(n721),
	.A(n720),
	.B(n719));
   on21_b U991 (.Q(\piece_0/N29 ),
	.A(n102),
	.B(n721),
	.C(n817));
   na21_b U992 (.Q(n802),
	.A(n722),
	.B(n798));
   eo21_b U993 (.Q(n724),
	.A(n723),
	.B(\piece_0/feedback [20]));
   mx21_b U994 (.Q(n726),
	.I0(n806),
	.I1(n809),
	.S(n724));
   or21_b U995 (.Q(\piece_0/N30 ),
	.A(n726),
	.B(n725));
   eo31_b U996 (.Q(n728),
	.A(\piece_0/feedback [21]),
	.B(n747),
	.C(n727));
   on21_b U997 (.Q(\piece_0/N31 ),
	.A(n102),
	.B(n728),
	.C(n817));
   on21_b U998 (.Q(n734),
	.A(n809),
	.B(n730),
	.C(n729));
   inv1_b U999 (.Q(n732),
	.A(n730));
   na21_b U1000 (.Q(n735),
	.A(n798),
	.B(n731));
   on31_b U1001 (.Q(n733),
	.A(n732),
	.B(n809),
	.C(\piece_0/feedback [22]),
	.D(n735));
   on31_b U1002 (.Q(\piece_0/N32 ),
	.A(\piece_0/feedback [22]),
	.B(n734),
	.C(n817),
	.D(n733));
   inv1_b U1003 (.Q(n736),
	.A(n738));
   on11_b U1004 (.Q(n740),
	.A(n736),
	.B(n809),
	.C(\piece_0/feedback [22]),
	.D(n735));
   on31_b U1005 (.Q(n739),
	.A(n809),
	.B(n738),
	.C(n741),
	.D(n737));
   on31_b U1006 (.Q(\piece_0/N33 ),
	.A(n741),
	.B(n740),
	.C(n817),
	.D(n739));
   en21_b U1007 (.Q(n743),
	.A(n742),
	.B(\piece_0/feedback [24]));
   mx21_b U1008 (.Q(n744),
	.I0(n798),
	.I1(n802),
	.S(n743));
   na21_b U1009 (.Q(\piece_0/N34 ),
	.A(n817),
	.B(n744));
   eo31_b U1010 (.Q(n746),
	.A(\piece_0/feedback [25]),
	.B(n747),
	.C(n745));
   on21_b U1011 (.Q(\piece_0/N35 ),
	.A(n102),
	.B(n746),
	.C(n817));
   on11_b U1012 (.Q(n750),
	.A(n603),
	.B(n748),
	.C(n747),
	.D(\piece_0/feedback [26]));
   en21_b U1013 (.Q(n751),
	.A(n750),
	.B(n749));
   on21_b U1014 (.Q(\piece_0/N36 ),
	.A(n102),
	.B(n751),
	.C(n817));
   eo31_b U1015 (.Q(n753),
	.A(n603),
	.B(\piece_0/feedback [27]),
	.C(n752));
   on21_b U1016 (.Q(\piece_0/N37 ),
	.A(n102),
	.B(n753),
	.C(n817));
   on21_b U1017 (.Q(n759),
	.A(n809),
	.B(n755),
	.C(n754));
   na21_b U1018 (.Q(n760),
	.A(n798),
	.B(n756));
   on31_b U1019 (.Q(n758),
	.A(n757),
	.B(n809),
	.C(\piece_0/feedback [28]),
	.D(n760));
   on31_b U1020 (.Q(\piece_0/N38 ),
	.A(\piece_0/feedback [28]),
	.B(n759),
	.C(n817),
	.D(n758));
   inv1_b U1021 (.Q(n761),
	.A(n763));
   on11_b U1022 (.Q(n765),
	.A(n761),
	.B(n809),
	.C(\piece_0/feedback [28]),
	.D(n760));
   on31_b U1023 (.Q(n764),
	.A(n809),
	.B(n763),
	.C(n766),
	.D(n762));
   on31_b U1024 (.Q(\piece_0/N39 ),
	.A(n766),
	.B(n765),
	.C(n817),
	.D(n764));
   en21_b U1025 (.Q(n767),
	.A(n769),
	.B(\piece_0/feedback [30]));
   mx21_b U1026 (.Q(n768),
	.I0(n798),
	.I1(n802),
	.S(n767));
   na21_b U1027 (.Q(\piece_0/N40 ),
	.A(n817),
	.B(n768));
   inv1_b U1028 (.Q(n771),
	.A(n773));
   or21_b U1029 (.Q(n770),
	.A(n806),
	.B(n769));
   on11_b U1030 (.Q(n775),
	.A(n771),
	.B(n809),
	.C(\piece_0/feedback [30]),
	.D(n770));
   on31_b U1031 (.Q(n774),
	.A(n809),
	.B(n773),
	.C(n776),
	.D(n772));
   on31_b U1032 (.Q(\piece_0/N41 ),
	.A(n776),
	.B(n775),
	.C(n817),
	.D(n774));
   en21_b U1033 (.Q(n777),
	.A(n779),
	.B(\piece_0/feedback [32]));
   mx21_b U1034 (.Q(n778),
	.I0(n798),
	.I1(n802),
	.S(n777));
   na21_b U1035 (.Q(\piece_0/N42 ),
	.A(n817),
	.B(n778));
   inv1_b U1036 (.Q(n781),
	.A(n783));
   or21_b U1037 (.Q(n780),
	.A(n806),
	.B(n779));
   on11_b U1038 (.Q(n785),
	.A(n781),
	.B(n809),
	.C(\piece_0/feedback [32]),
	.D(n780));
   on31_b U1039 (.Q(n784),
	.A(n809),
	.B(n783),
	.C(n786),
	.D(n782));
   on31_b U1040 (.Q(\piece_0/N43 ),
	.A(n786),
	.B(n785),
	.C(n817),
	.D(n784));
   en21_b U1041 (.Q(n787),
	.A(n789),
	.B(\piece_0/feedback [34]));
   mx21_b U1042 (.Q(n788),
	.I0(n798),
	.I1(n802),
	.S(n787));
   na21_b U1043 (.Q(\piece_0/N44 ),
	.A(n817),
	.B(n788));
   or21_b U1044 (.Q(n790),
	.A(n806),
	.B(n789));
   on11_b U1045 (.Q(n795),
	.A(n791),
	.B(n809),
	.C(\piece_0/feedback [34]),
	.D(n790));
   on31_b U1046 (.Q(n794),
	.A(n809),
	.B(n793),
	.C(n796),
	.D(n792));
   on31_b U1047 (.Q(\piece_0/N45 ),
	.A(n796),
	.B(n795),
	.C(n817),
	.D(n794));
   en21_b U1048 (.Q(n797),
	.A(n805),
	.B(\piece_0/feedback [36]));
   mx21_b U1049 (.Q(n799),
	.I0(n798),
	.I1(n802),
	.S(n797));
   na21_b U1050 (.Q(\piece_0/N46 ),
	.A(n817),
	.B(n799));
   inv1_b U1051 (.Q(n800),
	.A(n803));
   on11_b U1052 (.Q(n808),
	.A(n800),
	.B(n806),
	.C(n803),
	.D(n809));
   an21_b U1053 (.Q(n804),
	.A(n803),
	.B(n802),
	.C(n801));
   on41_b U1054 (.Q(n807),
	.A(\piece_0/feedback [36]),
	.B(n806),
	.C(n805),
	.D(n804));
   on31_b U1055 (.Q(\piece_0/N47 ),
	.A(\piece_0/feedback [37]),
	.B(n808),
	.C(n817),
	.D(n807));
   no21_b U1056 (.Q(n812),
	.A(n810),
	.B(n809));
   no21_b U1057 (.Q(n815),
	.A(n812),
	.B(n814));
   on11_b U1058 (.Q(n816),
	.A(\piece_0/feedback [38]),
	.B(n815),
	.C(n814),
	.D(n813));
   na21_b U1059 (.Q(\piece_0/N48 ),
	.A(n817),
	.B(n816));
endmodule

/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : P-2019.03
// Date      : Mon Jun  8 18:01:23 2020
/////////////////////////////////////////////////////////////
module chip (
	clk_p, 
	btn_rst_p, 
	sd_0_p, 
	sd_1_p);
   input clk_p;
   input btn_rst_p;
   output sd_0_p;
   output sd_1_p;

   // Internal wires
   wire LTIELO_3_NET;
   wire LTIELO_2_NET;
   wire LTIELO_1_NET;
   wire LTIELO_NET;
   wire LTIEHI_1_NET;
   wire LTIEHI_NET;
   wire [1:0] sd;
   wire clk;
   wire btn_rst;
   wire LVDD;
   wire LVSS;

   cvss_b LTIELO_3 (.Q(LTIELO_3_NET));
   cvss_b LTIELO_2 (.Q(LTIELO_2_NET));
   cvss_b LTIELO_1 (.Q(LTIELO_1_NET));
   cvss_b LTIELO (.Q(LTIELO_NET));
   cvdd_b LTIEHI_1 (.Q(LTIEHI_1_NET));
   cvdd_b LTIEHI (.Q(LTIEHI_NET));
   core u_core (.clk(clk),
	.reset(btn_rst),
	.sd_out(sd));
   SPACE_20 S1 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S2 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S3 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S4 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S5 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B S6 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B S7 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B S8 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B S9 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B S10 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B S11 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B S12 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B S13 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B S14 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B S15 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S16 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S17 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S18 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S19 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 S20 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W1 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W2 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W3 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W4 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W5 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T W6 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_BID_T W7 (.PAD(sd_0_p),
	.EN(LTIEHI_NET),
	.DO(sd[0]),
	.DIB(),
	.DI(),
	.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_BID_T W8 (.PAD(sd_1_p),
	.EN(LTIEHI_1_NET),
	.DO(sd[1]),
	.DIB(),
	.DI(),
	.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T W9 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T W10 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T W11 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T W12 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T W13 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T W14 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T W15 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W16 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W17 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W18 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W19 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 W20 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N1 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N2 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N3 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N4 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N5 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T N6 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T N7 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_BID_T N8 (.PAD(clk_p),
	.EN(LTIELO_1_NET),
	.DO(LTIELO_NET),
	.DIB(),
	.DI(clk),
	.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T N9 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T N10 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T N11 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T N12 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_BID_T N13 (.PAD(btn_rst_p),
	.EN(LTIELO_3_NET),
	.DO(LTIELO_2_NET),
	.DIB(),
	.DI(btn_rst),
	.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_T N14 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_T N15 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N16 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N17 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N18 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N19 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 N20 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E1 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E2 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E3 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E4 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E5 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B E6 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B E7 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B E8 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B E9 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B E10 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B E11 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B E12 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B E13 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_VDD_B E14 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_GND_B E15 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E16 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E17 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E18 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E19 (.LVDD(LVDD),
	.LVSS(LVSS));
   SPACE_20 E20 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_CNR_TR C1 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_CNR_BR C2 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_CNR_TL C3 (.LVDD(LVDD),
	.LVSS(LVSS));
   PAD_CNR_BL C4 (.LVDD(LVDD),
	.LVSS(LVSS));
endmodule

